### ISSUE TITLE
Globally unique process

### ISSUE THREAD

**Issue by princemaple** [c-rack/quantum-elixir#101]
Hi,

Quantum currently is only capable of running as a local process.
Mind if I send a PR to make it capable of running as a globally unique process as well?

Please let me know if there is anything that you'd concern about, or anything I should watch out for.

Thanks,
Po

**Comment by c-rack** [comment]
@princemaple thanks for asking!

We usually try to follow a "Problem / Solution" pattern in our development process (see closed issues, PRs and commits to get an idea). For your PR, it would be nice if code coverage would remain at 100%, but that is not a hard requirement. And if the new feature (I guess it will be configurable?) would get a paragraph in the README, that would be absolutely fantastic.

**Comment by princemaple** [comment]
@c-rack thanks for the quick reply.

> For your PR, it would be nice if code coverage would remain at 100%, but that is not a hard requirement.

I'd love to get this tested, but I have no idea how to test a feature that's only obvious in a cluster. I will, of course, make sure all the existing tests stay passed, though. Also, will make sure the global process still works in a single node.

> I guess it will be configurable?

Yes, only an opt in feature.

> And if the new feature would get a paragraph in the README, that would be absolutely fantastic.

No problem with that.

**Comment by princemaple** [comment]
sorry, referenced the PR itself instead of this issue.
