### ISSUE TITLE
Can't configure in separate packages under umbrella project

### ISSUE THREAD

**Issue by andrejsm** [c-rack/quantum-elixir#104]
If I configure `:quantum` in umbrella app in more than one package, the last one compiled overrides config thus throwing away all previous configuration.

A real life scenario. I've built an umbrella app where I have multiple packages and 2 of them have a jobs to be ran every 5 minutes. Unfortunately only one job is ran.

As a solution I configure both jobs in _main_ package's config.
What I want is to configure jobs in packages where they belong to. 

This would require to make a macro like Ecto has. Probably this could be added as an option not braking current approach.

**Comment by c-rack** [comment]
Interesting idea...
Contributions are welcome!
Please read about our [contribution process](https://github.com/c-rack/quantum-elixir#contribution) and feel free to submit a pull request.

**Comment by andrejsm** [comment]
I'll try to hop in within 2 - 3 months. Launching app soon and am busy right now.

**Comment by c-rack** [comment]
Sure, take your time. Good luck with your app!

**Comment by maennchen** [comment]
@andrejsm How do you imagine this new configuration solution?

Do we need a execution module inside of every umrella application like the ecto `Ecto.Repo`?

Are there other solutions to tell quantum in which configuration environments to search?

**Comment by andrejsm** [comment]
Probably a simple name-spacing would be sufficient.

For example:
```elixir
# config of MyFirstApp
config :quantum, my_first_app: [
  cron: [ ... ]
]

# config of MySecondApp
config :quantum, my_second_app: [
  cron: [ ... ]
]
```

And here in [Quantum.Application.start/2](https://github.com/c-rack/quantum-elixir/blob/5a45979309f5a1832d779d34de40f181eca5b3f8/lib/quantum/application.ex#L11) iterating through config props would extract all :cron occurrences and join them. Of course respecting if `:cron` is present as standalone prop.

With this we avoid `Ecto.Repo` alike technique where we have to create additional files. Or do just like with `Ecto.Repo`

**Comment by maennchen** [comment]
@andrejsm What do you think of #149 ?
