### ISSUE TITLE
support second granularity

### ISSUE THREAD

**Issue by trungpham** [c-rack/quantum-elixir#105]
Can we extend the crontab syntax to support seconds?
`* * * * *` will continue to run every minute
`* * * * * *` will run every second?

**Comment by theoretick** [comment]
I dont believe crontabs support a second-level granularity. IMO It would seem a bit heavy to add a superset of cron functionality to quantum, but that's just my 2 cents :).

One suggestion from SO is to make multiple jobs and offset them: 
```
* * * * * /path/to/executable param1 param2
* * * * * ( sleep 30 ; /path/to/executable param1 param2 )
```
http://stackoverflow.com/questions/9619362/running-a-cron-every-30-seconds

**Comment by trungpham** [comment]
The stackoverflow solution is a hack though. Would be nice if we can extend crontab syntax to support second-level granularity.

**Comment by c-rack** [comment]
@trungpham Thanks for opening this issue.
Do you want to run a job just every second or do you also want to run it every 2, 5, 15 seconds?

**Comment by trungpham** [comment]
It should allow the same syntax as the minute level since there are 60
seconds in a minute, and 60 minutes in an hour.

**Comment by c-rack** [comment]
Your suggestion is clear, but I still try to understand the problem you want to solve.

For example, would it be enough to introduce just a new `@every second` special form or do you need a `@every N seconds` expression or do you really need to restrict the job execution time additionally to minutes, hours, weekdays, months?

Could you please describe your use case? Maybe that makes the requirement more clear.

**Comment by sherbondy** [comment]
Hey there, I would love to be able to use quantum elixir to run a job every n seconds, where n is configurable. Right now considering rolling a basic genserver to do this but feels a little silly given this library already implements most of the desired functionality. Happy to have a go at a PR with a little guidance!

**Comment by sherbondy** [comment]
Would it be as simple as modifying:
https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/executor.ex

To have an execute fun that accepts "@every " <> n <> " seconds" as input and then does modular arithmetic on c.second value?

And tweaking convert_to_timezone to not zero out the second?

Or would I have to mess with normalizer / something else so that new schedule input is accepted as valid too?

Does having non-zero in canonical second value break any existing assumptions in the library?

Thanks for the guidance, gonna have a go at a fork!

**Comment by c-rack** [comment]
@sherbondy thanks for offering your help!

So let's introduce a new special form `@every N seconds` with `1 <= N <= 59`.

Given that this is a different kind of beast than the usual cron logic on per minute basis, I would not try to squeeze it in the existing workflow, but instead starting a dedicated process for it. Otherwise, quantum would need to wake up and check all jobs every second, even if there is no "every 1 second" job, something I would like to avoid in this library.

**Comment by sherbondy** [comment]
Hmm, okay, so this would entail optionally adding a second quantum worker to the supervision tree with a simplified timer (or even no timer) that sends after n seconds?

**Comment by c-rack** [comment]
Yes, something like that. Just give it a try 😄

**Comment by trungpham** [comment]
Are you guys concern with running the job every second? Shouldn't be an issue for the Erlang VM.
Also, can we support this syntax too?
```*/10 * * * * *``` run every 10 seconds.

**Comment by c-rack** [comment]
The planned new special form `@every 10 seconds` is semantically equal to your proposal and easier to read, too.

You have still not described the problem you want to solve, so I don't know why you want to use `*/10 * * * * *` rather than `@every 10 seconds`. Could you please clarify?

**Comment by trungpham** [comment]
I prefer the old school crontab syntax. :)

**Comment by c-rack** [comment]
Ok, so once @sherbondy has implemented the `@every N seconds` feature, feel free to submit a PR that quantum also supports it by understanding a `*/N * * * * *` syntax :-)

**Comment by princemaple** [comment]
Probably need to change this https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/timer.ex#L18 for `@every n seconds` to work. Might be a good idea to make this configurable...

**Comment by vertexclique** [comment]
Are there any development on this issue? Actually I need to have
> Run this job every n seconds

case also. It will really help.

**Comment by webzepter** [comment]
I also bumped into this issue

**Comment by venkatd** [comment]
Would be good to hear what the use cases are @trungpham  @vertexclique @webzepter @sherbondy

I haven't heard any use cases described, which makes it hard to determine if quantum is the right solution for second-level granularity.

**Comment by webzepter** [comment]
@venkatd I haven't waited for this feature and rewrite my background workers as GenServers in application supervision tree with 2-seconds repetition interval.

**Comment by venkatd** [comment]
@webzepter makes sense. I think this is the right move. IMO if you need to have a task that repeats every n seconds, a GenServer is probably the simplest approach and quantum would be overkill for that.

**Comment by minhajuddin** [comment]
Here is a sample GenServer implementation https://gist.github.com/minhajuddin/e083e2630959beb9616d894f5451ed9b

**Comment by maennchen** [comment]
I wrote a little library to parse / compose cron expressions. It also verifies dates against an expression, finds candidates for the next / previous execution date. It supports seconds from ground up.

Are you interested to implement this library here? https://github.com/sk-t/crontab

(The whole cron expression standard is implemented with the exception of the `W` modifier. This will be implemented another time.)

**Comment by c-rack** [comment]
@maennchen Thanks for your question. Generally, quantum should have as few dependencies as possible. How would your library add an enhancement to quantum? Parsing of cron expressions is already implemented and quite complete and the second-granularity feature is still waiting for someone who submits a pull request to add the `@every N seconds` feature, but maybe I am missing something and you can further elaborate your suggestion?

**Comment by maennchen** [comment]
@c-rack The library supports all of the cron feature. This inludes every modifier like `W`, `#` `L` etc.

You can see all of the features in this test here: https://github.com/sk-t/crontab/blob/master/test/crontab/functional_test.exs

**Comment by c-rack** [comment]
@maennchen OK, if there is a problem to solve, please feel free to submit a pull request and it will be merged according to our contribution policy.

**Comment by jclosure** [comment]
Bumped into this need myself.  Is anyone working on this yet?

**Comment by maennchen** [comment]
Yes, but i'm not working full time on the project where I need it, so it's going to take like another two weeks.

You can see the current state here: https://github.com/jshmrtn/quantum-elixir/tree/feature/use_crontab_hex
(I only plugged in the new library by now)

**Comment by maennchen** [comment]
Before I start to implement the second granularity Pull Request, I'd like to get your feedback.

You suggested the syntax `@every N seconds` to solve the second granularity.

With the pull request #144 there's a new option on how to implement this.

The `crontab` library brings a cron expression sigil with it. This creates new options on how to write the expressions in the configuration.

Example:
* `~e[1]` => Every minute
* `~e[1]e` => Every Second (`e` modifier stands for extended)

(This doesn't block us from still doing the `@every N seconds` syntax if you wish to implement it, but would be a good addition to support fine grained control of cron expressions.)

**Comment by maennchen** [comment]
Implementation question: Should minutely jobs always run at second 0 of a minute or should they be executed anytime in that minute?

**Comment by maennchen** [comment]
This change is currently implemented on master.

@c-rack Should we close this?

**Comment by cschiewek** [comment]
👋 

Thanks for the great lib!  I'm curious how you get second granularity via config.  If I try to use the `~e[]` or the `%Crontab.CronExpression{}` i get function not defined errors.  Thoughts?

**Comment by maennchen** [comment]
@cschiewek See #156
