### ISSUE TITLE
Problem: Dependencies satisfaction issue 

### ISSUE THREAD

**Issue by luki3k5** [c-rack/quantum-elixir#117]
In the latest version of elixir + phoenix + timex project we have a problem with satisfying all dependencies due to the fact that quantum expects version of times from branch 2.x.x while we use 3.x.x and some other dependencies need it too. 

I will offer a quick PR with just the version bump.

**Comment by luki3k5** [comment]
Okay, my bad - I actually checked the mix.exs for quantum and it looks like it is using 3.x.x - however I still see this in our app: http://take.ms/WqHdv

**Comment by c-rack** [comment]
@luki3k5 you are right, this change is not released yet:
https://github.com/c-rack/quantum-elixir/compare/v1.7.1...HEAD

As it's quite a while since last release, I will publish version 2.0 (with timex 3 and elixir 1.3 requirements) this week.

**Comment by luki3k5** [comment]
sounds great, thank you.

**Comment by theoretick** [comment]
@c-rack Regarding the new version, is there an existing project policy in place for versioning? Since we're talking about bumping to v2 for updated dependencies should this be a major release or maybe just v1.8?

Note, I have no strong opinion about this, just something that came to mind from this issue :)

**Comment by c-rack** [comment]
@theoretick this project uses [Semantic Versioning 2.0.0](http://semver.org/), as stated in the [changelog](https://github.com/c-rack/quantum-elixir/blob/master/CHANGELOG.md). I agree that next version should be 1.8.0, then. Thanks for your comment!

**Comment by c-rack** [comment]
Version 1.8.0 has been released:
https://hex.pm/packages/quantum

@luki3k5 would you please check and close this issue then?

**Comment by luki3k5** [comment]
Hello @c-rack I just did and it works flawlessly. Thank you!
