### ISSUE TITLE
Jobs queue is not shared across nodes when `global?` is true

### ISSUE THREAD

**Issue by mdowell12** [c-rack/quantum-elixir#120]
I have an application that is running across multiple nodes.  I'd like to have one global Quantum.jobs queue whose updates are reflected across all of the nodes in my cluster.  E.g. if one of my nodes removes a job from the queue, I'd like that change to be visible on all other nodes in the cluster.

I've played around with this setting:

    config :quantum, global?: true

but did not see any changed behavior.  After quickly searching the code base, it seems to me that this isn't implemented yet.  Is that true?  If so, do you have plans for implementing it in the future?

My application is pointing to commit https://github.com/c-rack/quantum-elixir/commit/a328df47d969ed0167e9e28245e4884914c2e150.

**Comment by c-rack** [comment]
It should be implemented by using `{:global, Quantum}` as process name here:
https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum.ex#L23-L25

That feature was introduced by https://github.com/c-rack/quantum-elixir/pull/102

@princemaple any idea why this could be not working for @mdowell12 ?

**Comment by princemaple** [comment]
@mdowell12 what behavior are you seeing?
Could you share some code and your architecture?

**Comment by mdowell12** [comment]
@princemaple, certainly.

My application has two nodes that dynamically add/remove jobs.  I've tried to configure Quantum to run globally by adding the following to my config file:

    config :quantum, global?: true

But when I add/remove jobs on one node, I don't see those changes reflected on the other node.  I also did some digging on the global module and couldn't find any references to Quantum.  For example, running `:global.registered_names` returned an empty list.

Here's the code to add a job:

    job = %Quantum.Job{
                    nodes: [node()],
                    overlap: false,
                    schedule: cron_format,
                    timezone: cron_tz,
                    task: fn -> do_something end
                }

    Quantum.add_job("#{name}", job)

We're running erlang 18 and Elixir 1.2.3.  We're also pointing to commit a328df47d969ed0167e9e28245e4884914c2e150 on this repo and running Timex 2.1.6.

**Comment by princemaple** [comment]
@mdowell12 
Does quantum work for you when you don't set `global?: true`?
Do you have the two nodes clustered?
Also, for dynamically added jobs, I'd recommend using separate processes. The only reason you should use `global` is when you have a cluster of nodes *AND* you have predefined jobs *AND* the work done by the jobs may overlap.

**Comment by mdowell12** [comment]
@princemaple it does work when I don't set `global?: true`, just not in the distributed way that I've described.  The two nodes are clustered.

And what are the separate processes you're recommending?  You mean outside of Quantum?  Do you see any way that Quantum could be used to solve this problem?

**Comment by princemaple** [comment]
I meant when you don't set global, dynamically added jobs are executed on
the node that they are added on, unless you specify a different node when
you add the jobs. What's your expected behavior?

**Comment by mdowell12** [comment]
Yep, that's the behavior we get.  We're using the cluster to provide a highly available web service, though, so the behavior you described doesn't allow for any fail-over.  Ideally, when our application adds a job to the Jobs queue, we'd see that reflected across both nodes (but obviously only run by one node).  Same for removing/updating jobs.

**Comment by princemaple** [comment]
I'm afraid that after all global isn't the option you should be looking at.
Are you talking about dynamically added repeated jobs or dynamically added
one-time jobs, I'd like to confirm this before making further suggestions.

**Comment by mdowell12** [comment]
No worries, I appreciate the attention and advice!  We're dynamically adding repeated jobs.

**Comment by princemaple** [comment]
So you want to deal with node failures, not process failures. You will
probably have to add some external cache to store the job definitions for
everyone node. Leave quantum in normal mode. Load jobs from the external
cache when node restarts. You can use any cache infrastructure, but I would
use an Elixir app :) that would allow you to add it to the cluster directly
and save you from rolling your own serialization strategy. I can understand
why you were trying to use global. The problem is, a global process is not
something runs above the whole cluster, but simply runs as a globally
unique process. It fails with node failure too. There is no automatic
restoration of global process across nodes. I wish there was. I'd love to
know that I'm wrong.

**Comment by mdowell12** [comment]
Ah, makes sense.  I will talk with people on my team and try to devise a strategy that works for us.  Thanks again for the advice!  I'll close the issue for now, but will post here if we come up with anything interesting.

**Comment by terencechow** [comment]
@mdowell12 Do you have a solution you can share or any guidance?
