### ISSUE TITLE
failed to use timex version 2.2.1

### ISSUE THREAD

**Issue by egeersoz** [c-rack/quantum-elixir#124]
I get this when I run `mix deps.get` after adding `{:quantum, ">= 1.8.0"}` to my mix.ex file:

```
Failed to use "timex" (version 2.2.1) because
  phoenix_timex (version 1.0.1) requires ~> 2.1
  quantum (version 1.8.0) requires ~> 3.0
  timex_ecto (version 1.1.3) requires ~> 2.1
  Locked to 2.2.1 in your mix.lock
```

Elixir 1.3.2, Phoenix 1.2.1

**Comment by c-rack** [comment]
@egeersoz timex is not used anymore as a dependency, so I close this issue. Feel free to reopen it if the problem persists with current version 1.8.1.
