### ISSUE TITLE
Job didnt start? 

### ISSUE THREAD

**Issue by ijunaid8088** [c-rack/quantum-elixir#125]
I have added job in my `config/prod.ex` file.. as

```
config :quantum,
  cron: [
    snapshot_extraction: [
      task: {"Extractor.SnapExtractor", "extract"},
      schedule: "@daily",
      overlap: false
    ]
  ]
```
But it didnt start.. And also there is not logs in heroku for it. If it started or failed. Am I doing something wrong or I can check weather its running or not?

**Comment by c-rack** [comment]
Did you add quantum to the list of applications in your mix.exs file like this?

```elixir
def application do
  [applications: [:quantum]]
end
```

**Comment by ijunaid8088** [comment]
Yeah I have done this 

https://github.com/ijunaid8088/extractor/blob/master/mix.exs#L22

**Comment by c-rack** [comment]
OK, then please try to replace your task with `fn -> IO.puts "Tick" end` and your schedule with `* * * * *`. Since you have set the schedule to `@daily`, it will start at next midnight, so you do not see any execution on application start if starting during the day.

**Comment by ijunaid8088** [comment]
Okay now its working.. I removed it from PROD and add it to straight config file. Thanks

**Comment by ijunaid8088** [comment]
It worked locally.. and very good as i expected.. but again.. it didn't in
production.

**Comment by c-rack** [comment]
Maybe an heroku specific problem?
See issue https://github.com/c-rack/quantum-elixir/issues/60
