### ISSUE TITLE
How to edit a Quantum at runtime?

### ISSUE THREAD

**Issue by egeersoz** [c-rack/quantum-elixir#129]
First of all, thanks for the awesome library! :)

I'm looking for a way to edit a Quantum at runtime, specifically change its schedule and the task it is performing. I know there is a way to find jobs by name by doing `Quantum.find_job(name)` but after finding it I also need to change its task.

The reason is that I have a wrapper around Quantums, called Jobs, that users can create/edit/delete. The details of a job, such as its frequency, can be edited by a user. When such an edit is performed, I then need to edit the underlying Quantum. For example, if the user initially creates the Job with a 24 hour schedule, then changes it to a 6 hour schedule, I need to somehow make that change on the Job's Quantum. Right now I'm deleting the Quantum and creating & activating a new one, but doing that doesn't feel very elegant.

**Comment by c-rack** [comment]
Thanks for your question!

Currently, you would need to use `delete_job/1` and `add_job/2` to update an existing job. A new function `update_job` would be great, but is currently not implemented. Any contributions in that direction are welcome!

**Comment by egeersoz** [comment]
Gotcha. When you say "to update an existing job" what do you mean? Using `delete_job` and then `add_job` creates a brand new job with a brand new PID, right?

It's not a big deal, I already wrote the code to do it - I'm just curious. Thanks! :)

**Comment by c-rack** [comment]
@egeersoz Yes, deleting and adding a job leads to a new PID.

Feel free to send a PR to bring your "update an existing job" to the code base. I'll merge it. If you don't want to send a PR, please close this issue.

**Comment by c-rack** [comment]
@egeersoz any update on this? can we close this issue?
