### ISSUE TITLE
Cron job in quantum for every 2 hours

### ISSUE THREAD

**Issue by ijunaid8088** [c-rack/quantum-elixir#130]
Is this a right way of doing it?

```
config :quantum,
  cron: [
    snapshot_extraction: [
      task: {"Extractor.SnapExtractor", "extract"},
      schedule: "0 */2 * * *",
      overlap: false
    ]
  ]
```

**Comment by overallduka** [comment]
I believe so, you can use this tool: http://crontab.guru/#0_*/2_*_*_* to build cron expressions easily.

**Comment by c-rack** [comment]
@ijunaid8088 Yes, with that schedule, it will start the job on 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 20 and 22 o'clock. If you want to run it a odd hours, you would need to define it as a comma separated list: `0 1,3,5,7,9,11,13,15,17,19,21,23 * * *`.

Question answered?

**Comment by ijunaid8088** [comment]
@c-rack Yes Answered! 

Why it seems as you are not telling me but fighting with me?

**Comment by c-rack** [comment]
@ijunaid8088 what do you mean with "fighting"? Please excuse if anything in my response seems to be aggressive in any way, that was not intended.

**Comment by ijunaid8088** [comment]
@c-rack Yes, that. "Question answered?" Doesn't seem to be polite for a beginner. But it's fine. I just took it in an offensive way!

**Comment by c-rack** [comment]
OK, thanks for explaining, I'll do it better next time! I appreciate any question, bug report and contribution to this project.

**Comment by ijunaid8088** [comment]
@c-rack You are welcome!
