### ISSUE TITLE
problem with timex, local time and a switch of hour...

### ISSUE THREAD

**Issue by matteosister** [c-rack/quantum-elixir#132]
Hi everybody!

First of all thanks for your awesome work! We are using quantum in production for many months now, and everything is great.

Yesterday we had a problem with a change of local time. At 2 am the hour forward to 3 am, and for an hour Timex was creating an AmbiguousDateTime instead of a normal DateTime. We are using quantum with **:local** and I was watching the code to understand what could be the origin of the bug. 

I see that in [this commit](https://github.com/c-rack/quantum-elixir/commit/b453fc3e9f15b669bf0187160af6500ba0663c1a) by @lau you are switching from timex to calendar, and seems like you are disallowing the use of :local at all (the readme still says it's possible, but it's only on master right now).

Two question:
- why did you switch from timex to calendar?
- why you are disallowing :local at all?

Any suggestions about what we can do achieve a reliable "9 am" task when the hour switch, even if we use UTC?

Many thanks in advance.

this is the stack trace for the bug.

```
Task #PID<0.17732.1> started from Quantum terminating 
** (Protocol.UndefinedError) protocol Timex.Protocol not implemented for #<Ambiguous(#<DateTime(2016-10-30T02:00:00+02:00 Europe/Rome)> ~ #<DateTime(2016-10-30T02:00:00+01:00 Europe/Rome)>)>
     (timex) lib/protocol.ex:1: Timex.Protocol.impl_for!/1
     (timex) lib/protocol.ex:36: Timex.Protocol.to_datetime/2
     (timex) lib/timezone/timezone.ex:343: Timex.Timezone.convert/2
     (quantum) lib/quantum/executor.ex:83: Quantum.Executor.execute/2
     (elixir) lib/task/supervised.ex:94: Task.Supervised.do_apply/2
     (elixir) lib/task/supervised.ex:45: Task.Supervised.reply/5
     (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3 Function: &Quantum.Executor.execute/2     Args: [{"30 10 * * *", {Atreyu.Worker, :run}, [], :local}, %{d: {2016, 10, 30}, h: 2, jobs: [nil: %Quantum.Job{args: [], name: nil, nodes: [:"atreyu@host-machine"], overlap: true, pid: #PID<0.17700.1>, schedule: "30 10 * * *", state: :active, task: {Atreyu.Worker, :run}, timezone: :local}, nil: %Quantum.Job{args: [], name: nil, nodes: [:"atreyu@host-machine"], overlap: true, pid: #PID<0.17701.1>, schedule: "0 2 * * *", state: :active, task: {Atreyu.ClaimsImporter, :import}, timezone: :local}, nil: %Quantum.Job{args: [], name: nil, nodes: [:"atreyu@host-machine"], overlap: true, pid: #PID<0.17702.1>, schedule: "*/30 * * * *", state: :active, task: {Atreyu.Email.Alert, :send}, timezone: :local}, nil: %Quantum.Job{args: [], name: nil, nodes: [:"atreyu@host-machine"], overlap: true, pid: #PID<0.17703.1>, schedule: "*/5 * * * *", state: :active, task: {Atreyu.Testate.Hydrator, :manage}, timezone: :local}, nil: %Quantum.Job{args: [], name: nil, nodes: [:"atreyu@host-machine"], overlap: true, pid: #PID<0.17704.1>, schedule: "0 5 * * *", state: :active, task: {Atreyu.Testate.Fetcher, :fetch}, timezone: :local}], m: 0, r: 0, w: 0}]
```

**Comment by c-rack** [comment]
@matteosister thank you for opening this issue!

@lau I think you can explain best about the rationale behind these changes?

Regarding support for `:local` support, I would like to keep supporting it, too, because there are valid use cases for that (like the example you provided).

**Comment by matteosister** [comment]
@c-rack After reasoning about it a little, I think that maybe using a local timezone for a crontab app could be really error prone. In our case, if you say local time at 2:30 am, you got 2 occurrence of the same hour in the same day. After some talks with my devops collegue, he said that with lambda functions (that do not support timezones) he had to schedule every hour, and, at the application level, after casting the date to local, decide what to do. Maybe this is the main reason why @lau disabled the functionality?

**Comment by lau** [comment]
@matteosister look at this: http://www.creativedeletion.com/2015/08/07/why-not-to-use-server-local-time.html

Is your server time zone set to something other than UTC?

> We are using quantum in production for many months now, and everything is great.

With date and time bugs it can take many months or even several years before you run in to the hidden bugs. For instance ones that are related to DST or leap years.

> Any suggestions about what we can do achieve a reliable "9 am" task when the hour switch, even if we use UTC?

Does it really need to be 9am in local time every day? Could you define it in UTC so that in local time it will be one hour earlier or later depending on summer-time / DST?

**Comment by matteosister** [comment]
@lau we have some servers (in fact containers) that have timezone set to local because of a bigger problem with a mysql database and a php application. Believe me, you don't want to know :smile: 

We are trying to solve the problem, because we already learned (the hard way) how bad this thing is.

> Does it really need to be 9am in local time every day? Could you define it in UTC so that in local time it will be one hour earlier or later depending on summer-time / DST?

it has to be at that time. It deals with online payments. But we can easily solve the problem at the application level by executing every hour the quantum job, convert to local timezone inside elixir and act accordingly. It's just a matter of a function call with pattern matching on the hour. Not a big deal.

I'm asking this just because I wanted to know your criteria on taking this decision. I totally agree with the choice of getting rid of the _:local_ configuration, because it can create many sneaky bugs.

You didn't answer about the timex vs calendar question. Why? It's just a matter of taste? (you are the creator of calendar, so it makes sense) Or do you think that timex is doing something wrong?

@c-rack close this issue whenever you want
