### ISSUE TITLE
Crontab format not running

### ISSUE THREAD

**Issue by rafaeljesus** [c-rack/quantum-elixir#133]
Hey guys,

I don't know if I'm missing something here but this config is not running at the desired time:

```ruby
config :quantum, cron: [
 "30 11 * * *  MyModule.SendSms.perform"
]
```

It should run at 11:30 AM right? I tried several other combinations and waited to see if it triggers locally but the only one I see working was each 1 min `* * * * *`

quantum: 1.8.0
timex: 3.1.5

I'd appreciate any help,

Cheers

**Comment by rafaeljesus** [comment]
I have tested here using a similar node.js [lib](https://github.com/node-schedule/node-schedule)

It runs at 14:15 PM:
```javascript
const schedule = require('node-schedule')

schedule.scheduleJob('15 14 * * *', () =>
  console.log('----------'))```
```

I used the same expression on quantum to run at 14:20 PM:
```ruby
config :quantum, cron: [
 "20 14 * * *": fn -> IO.puts("------") end
],
timezone: :local
```

But the quantum version is not working as well

**Comment by c-rack** [comment]
@rafaeljesus two questions:

1. Which time zone are you using? Quantum uses UTC by default (yes, I have seen that you are setting timezone to `:local` in your second comment :)).
2. Have you started quantum by adding it to the list of applications?

Thanks,
Constantin

**Comment by rafaeljesus** [comment]
Hi @c-rack thank you for your quick reply!

I am using my default mac timezone which is Brasilia Summer Time (Brazil). As you can see I tested with `:local` and the default one `:utc`

Yes I added quantum on application list, also tried adding as the first element of the list and as the last just to check if it would be conflicting with some other lib.

I just tested here again on other mac and still not working, I'll create a simple mix project and test quantum as a unique dependency

**Comment by rafaeljesus** [comment]
It seems that I can not pass a string to `timezone:` key
```ruby
# should run at 10:30 AM
config :quantum,
  cron: [
    "30 10 * * *": fn -> IO.puts("Hey it works!!") end
  ],
  timezone: "America/Sao_Paulo"
```

It throws `** (RuntimeError) Unsupported timezone: America/Sao_Paulo` so it is using the UTC timezone even if I pass `:local` to it,

So to work out, I must to take the difference out using UTC:
```ruby
# It runs at 10:30 AM but I must to +2
config :quantum,
  cron: [
    "30 12 * * *": fn -> IO.puts("Hey it works!!") end
  ]
```

**Comment by c-rack** [comment]
@rafaeljesus have you tried latest master branch instead of hex.pm published version? it should support passing the timezone as `America/Sao_Paulo`. If that works for you, I could publish a new version to hex.pm over the weekend.

**Comment by c-rack** [comment]
@renews Thanks! I'll publish a new version shortly.

@rafaeljesus Have you tried master branch as well?

**Comment by rafaeljesus** [comment]
Sorry mates, I'm going to test right now

**Comment by rafaeljesus** [comment]
@c-rack Thank you for working on this on the weekend mate, it works now 🎉

**Comment by c-rack** [comment]
As version 1.8.1 is released to hex.pm, I close this issue.
