### ISSUE TITLE
How to handle application crashes?

### ISSUE THREAD

**Issue by terencechow** [c-rack/quantum-elixir#136]
I asked this on stackoverflow, but maybe i might get better direction here...

How would I go about ensuring that my cron jobs exist pass application restarts? Right now I am adding cron jobs dynamically, ie when someone POSTs to a specific route, I use `Quantum.add_job`. I save the details of the cron job in my `Ecto.repo` as well. 

Given that, how would I ensure my cron jobs persist through an application restart? I anticipate I will be hosting my application on Google Compute Instances and every now and then I can foresee those compute instances needing a reset. 

Right now I'm thinking of a Reboot process that simply runs through the cron jobs in my Repo and does `Quantum.add_job` on each of them, but if there is a more appropriate way, any guidance  would be greatly appreciated. 

Apologies if the answer is obvious, I am quite new to elixir, genservers, etc. Thanks!

**Comment by c-rack** [comment]
@terencechow your idea sounds perfectly ok to me!

**Comment by terencechow** [comment]
Am going to close this. For anyone visiting this in the future I used the below for my reboot:

`worker(Task,[MyApp.MyRebootModule, :reboot, []], restart: :transient),`

where `reboot` is the name of the function in `MyRebootModule`

**Comment by c-rack** [comment]
@terencechow thanks!
