### ISSUE TITLE
[Question] Is it possible to run a task only once on a specific time? 

### ISSUE THREAD

**Issue by ourway** [c-rack/quantum-elixir#143]
I need to run a task 3 days later.  And I don't want it to be periodic.  It it possible in Quantum?

**Comment by c-rack** [comment]
@ourway thanks for your question. This is currently not possible with Quantum. I could imagine a new crontab expression like `at 2017-12-31T23:59:59Z` to provide this functionality, but this is currently not implemented. Any contributions in that directions are appreciated.

**Comment by maennchen** [comment]
You could also just use [`Process.send_after/4`](https://hexdocs.pm/elixir/Process.html#send_after/4) to implement your problem.

```elixir
Proccess.send(pidOfProcessToExecute, :execute, 1000 * 60 * 60 * 23 * 3)
```

If blocking of the thread is no problem, you could also use [`Process.sleep/1`](https://hexdocs.pm/elixir/Process.html#sleep/1) to wait until you execute the job.

```elixir
Process.sleep(1000 * 60 * 60 * 23 * 3)
```

If you want to implement it, you could also schedule a job with a very specific cron expression. This could for example be `59 23 31 12 * 2017` to run on `2017-12-31T23:59:00Z`.

**Comment by maennchen** [comment]
@ourway Can we close this issue?

**Comment by ourway** [comment]
Ya, Thanks
