### ISSUE TITLE
Multiple Executors

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#152]
Refactor the library to provide an `Executor` behaviour for an application.

The solution should be similar like the `Ecto.Repo` behaviour and its configuration.

**Comment by maennchen** [comment]
@c-rack Would you prefer this next to the current executor (avoid BC breaks) or clean with BC breaks?

**Comment by c-rack** [comment]
@maennchen I always prefer clean solutions :-) If it breaks BC, we just bump the version accordingly, but maybe we find a way that does not break it?

**Comment by maennchen** [comment]
If we create a worker for each application (like `Ecto.Repo` does), then I'd also like to remove the worker we have now.

In a clean solution there should be only be one way to start a scheduler.

**Comment by maennchen** [comment]
@c-rack Is it ok for you if I create a v2 branch and point my PR there? I'd like to add some other tickets in the V2 branch too before we create a release.

**Comment by maennchen** [comment]
@c-rack Ok, just do not release a new version, If we do BC anyways, I want to do BC just once.
