### ISSUE TITLE
Is there any standardized way to handle exceptions during quantum execution?

### ISSUE THREAD

**Issue by asiniy** [c-rack/quantum-elixir#158]
subj.

**Comment by c-rack** [comment]
Fixed by #164

**Comment by asiniy** [comment]
Still can't understand how to do it

**Comment by asiniy** [comment]
@maennchen

**Comment by maennchen** [comment]
@asiniy If it fails now, the Task Supervisor will crash. You can implement standard OTP error handling.

**Comment by maennchen** [comment]
The error handling will also improve with #137. If tasks fail, the cron runner itself will also restart.

You could also put the supervisors of your app onto the same level as the task supervisor. This way your whole app will be restarted if the right supervision strategies are used.

@asiniy Do you still have questions?

**Comment by asiniy** [comment]
@maennchen let me think for some time, please
