### ISSUE TITLE
Problem: Named jobs

### ISSUE THREAD

**Issue by alPacino** [c-rack/quantum-elixir#16]
It would be great to have named scheduled jobs like this:

```
config :quantum, cron: [
  news_letter: "* * * * * MyApp.NewsLetter.send",
  weekly_news_letter: "@weekly MyApp.NewsLetter.send",
  stats_gathering: "* * * * * MyApp.Stats.gather",
  daily_stats_gathering: "@daily MyApp.Stats.gather"
]
```
Or using another (extended) form:

```
config :quantum, cron: [
  news_letter: [
    schedule: "* * * * *",
    task: "MyApp.NewsLetter.send" # maybe {MyApp.NewsLetter, :send} will be supported too
  ] 
]
```

This also may be useful for pausing/deleting jobs using its names.

Also extended format allows to define some additional params for tasks like `shutdown` (for `TaskSupervisor`) and others.

As for `shutdown`. Let's say there is a job which always takes at least 120 seconds. So it will be able to set `shutdown` to 120000 (milliseconds) or more and be sure that certain job will not be killed before completion.

But `shutdown` option still depends on the question I asked on Stackoverflow ([Elixir Task - Graceful shutdown](http://stackoverflow.com/questions/31977215/elixir-task-graceful-shutdown)). Unfortunately I don't have solution so far.

**Comment by c-rack** [comment]
@alPacino which form do you prefer?

**Comment by alPacino** [comment]
@c-rack I prefer this form:
```
config :quantum, cron: [
  news_letter: [
    schedule: "* * * * *",
    task: "MyApp.NewsLetter.send", # maybe {MyApp.NewsLetter, :send} will be supported too
    args: [:monthly],
    shutdown: 30, # in seconds
    overlap: false,
    log_file: "/var/log/news_letters.log",
    log_level: :warn
  ] 
]
```

because it allows to set other options for a job. Let's say additional params, some other options like "Should Quantum overlap certain job or not" (belongs to issue [Problem: long-running jobs could overlap #8](https://github.com/c-rack/quantum-elixir/issues/8)) etc.

Defined above config example shows how this form can be used. So I'm sure it is quite flexible for new features.

**Comment by c-rack** [comment]
I agree with your proposal regarding the form. It allows to extending the functionality without breaking backward-compatibility.

What do you think if we use questions as keywords? For example
```
newletter: [
  when: "@weekly",
  what: "MyApp.Newsletter.send",
  how: [overlap: false, shutdown: 30]
]
```

**Comment by alPacino** [comment]
Sorry, but I don't think the question-like form may be useful for new options/features. Examples:

- we will have to enhance `what` section to use `args` option like this
```
newletter: [
  ...
  what: {"MyApp.Newsletter.send", [1, 2, 3]},
  # or
  what: [
    some_key: "MyApp.Newsletter.send",
    args: [1, 2, 3]
  ],
  ...
]
```
- if we need to define `log_*` options they don't belong to `how` question I think.

Moreover we can't predict all options that can be used here in future so that we don't know what questions would be suitable. For logging we can use keyword `where` (where to log), but also it can be used to define app node(s) where certain task should be run on (BTW this may be really useful feature too).

Of course I don't want to impose my suggestion concerning config form, the statements above are just my vision :)

**Comment by c-rack** [comment]
Convinced :)

Let me suggest to implement only the currently used keywords and discuss/implement the others (overlap, etc) in separate issues.

Would you like to work on this issue and send a PR?

**Comment by alPacino** [comment]
Yes, will implement this with pleasure :) So we're going to support first 3 keywords:
- `schedule` (required)
- `task` (required)
- `args` (optional, default: [])

P.S. of course each feature will be discussed in separate issue, overlap was mentioned just for example, sorry :)

**Comment by c-rack** [comment]
Fantastic. You have now contributor status (which means you can also merge PRs) and are assigned to this issue.

**Comment by alPacino** [comment]
Thanks @c-rack :) Let me push into my fork first for code review. I've implemented also task suspension/deletion. I'd like the master of this repo to be stable and applicable.

**Comment by c-rack** [comment]
@alPacino I saw your commit https://github.com/alPacino/quantum-elixir/commit/eadaee1334b6480a0956662c772046a41b8766f5.
Is it ready for review or work in progress? :)

**Comment by alPacino** [comment]
@c-rack It's ready for review :)

**Comment by c-rack** [comment]
Cool, thanks. Could you please send a PR?

**Comment by alPacino** [comment]
Sure, I guess there are no objections :)

**Comment by c-rack** [comment]
Not really. Your change solves a well described problem, so it should be merged.

**Comment by alPacino** [comment]
Merge accomplished

**Comment by c-rack** [comment]
Closed by merging https://github.com/c-rack/quantum-elixir/pull/18
