### ISSUE TITLE
Move Documentation into ExDoc

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#162]
It would be nice to move the documentation into ExDoc as custom Pages.

The documentation is growing and it would be nice to split it into separate pages.

Does anyone have reasons not to do that? Otherwise I'll make a PR.

**Comment by maennchen** [comment]
I'd propose to leave a basic example and the the setup inside of the README and link all further things to ExDoc.

**Comment by c-rack** [comment]
Sounds good to me

**Comment by c-rack** [comment]
Closed by #165 and #166
