### ISSUE TITLE
OTP release generation fails on cron expression in config

### ISSUE THREAD

**Issue by supernintendo** [c-rack/quantum-elixir#169]
Attempting to create an OTP release (in this case with `exrm`) with cron expressions defined in quantum config causes the build to fail. With the following in `config.exs`:

```
config :quantum,
  cron: [
    "0 * * * *": &ExampleProject.ExampleTask.call/0,
  ]
```

I get the following error after building the release:
```
Cannot add file sys.config to tar file - [{error,{87,erl_parse,["syntax error before: ",["Fun"]]}}]
===> Provider (tar) failed with: {error,
                                         {rlx_prv_archive,
                                          {tar_unknown_generation_error,
                                           "example_project","1.0.0"}}}

==> ERROR: "Unknown error occurred when generating tarball for example_project-1.0.0\n  Do you have any file names longer than 100 characters? That is a known issue with systools."
```

With line 87 of sys.config being quantum's config. Removing quantum from `config.exs` allows for a successful build. My guess is that this has to due with how the asterisks are treated in the compiled Erlang source... perhaps they need to be escaped?

**Comment by maennchen** [comment]
If you use `exrm`, please use the `{ModuleName, :function_name}` notation instead of `&ModuleName.function_name/arity`.

**Comment by maennchen** [comment]
Does this resolve your problem?

**Comment by supernintendo** [comment]
@maennchen That did the trick, thanks! Closing this...
