### ISSUE TITLE
Timezone not being set from config/defaults

### ISSUE THREAD

**Issue by boxxxie** [c-rack/quantum-elixir#171]
config.exs
```
use Mix.Config

config :quantum,
  global?: true,
  timezone: "America/New_York"
```

when i make jobs with or without a timezone key they get a `:utc` value, regardless of what i assign
`Quantum.jobs |> IO.inspect`

```
[fetch_daily_files: %Quantum.Job{args: [:ok], name: :fetch_daily_vb_files,
  nodes: [:nonode@nohost], overlap: false, pid: #PID<0.224.0>,
  schedule: ~e[* * * * * *], state: :active,
  task: {ModuleName, :fetch_daily_files}, 
  timezone: :utc}]
```

**Comment by maennchen** [comment]
Hey @boxxxie 

The default timezone is not represented in the job (currently).

https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/timer.ex#L10

Does it really not work for you (it executes at the wrong times) or did you just expect the `job.timezone` to be what you configured?

**Comment by maennchen** [comment]
Replaced by #172
