### ISSUE TITLE
Problem: Unclear Timezone Handling

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#172]
The timezone handling seems to cause some questions. (See #171 )

It is also not how I would expect it to work.

My expectations:

* The configuration parameter exists to provide default values for the `job.timezone`.
* The Quantum Worker does not care about time anymore, it just fires every second.
* When a Job is executed, the current time is calculated (derived from the `job.timezone`)
* The job is checked against this time.

**Comment by maennchen** [comment]
@c-rack Do you share this view on the problem?

**Comment by maennchen** [comment]
I propose to only support the `default_timezone` config variable. The config value is really easy understood. The global `timezone` should be removed.

**Comment by c-rack** [comment]
Agreed 👍

**Comment by maennchen** [comment]
Solved with #181
