### ISSUE TITLE
Release V2

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#184]
* [x] Docs ( #186 )
* [x] `crontab` support for `calendar` (Completely Independent Now)
* [x] Pin released version of `crontab`. (jshmrtn/crontab#40)
* [x] #180 Run Strategies
* [x] Test `master` by hand
* [x] Merge #187 
* [x] Fix #189 
* [x] Fix #204 
* [x] Fix #207 
* [x] Fix #214 
* [x] Merge #225 
* [x] Merge #224 
* [x] Merge #226 
* [x] Release `v2.0.0-beta.2`
* [x] Fix #227 
* [x] Some more testing
* [x] Release `v2.0.0` #229 

⚠️  **Help Wanted to check documentation and try `master` before we release.** ⚠️

**Comment by maennchen** [comment]
@c-rack Would you create a beta release? I'd like to get some other users to test the changes.

**Comment by c-rack** [comment]
Which version shall I use? 2.0.0-beta? 2.0.0-rc1?

**Comment by maennchen** [comment]
`2.0.0-beta.1` ?

**Comment by matthewlehner** [comment]
I'm just getting started setting up Quantum and will use the current commit on master as a reference. If I notice anything out of the ordinary that doesn't seem to be working I'll submit PRs for doc fixes.

That said, I'd love an 'official' beta release on hex, if it's in the works! :)

**Comment by maennchen** [comment]
@c-rack ping (hex beta release)

**Comment by c-rack** [comment]
Yeah, I will release it tomorrow afternoon. Sorry for the delay!

**Comment by matthewlehner** [comment]
@c-rack Sorry to bug you again, but before you release a 2.0 beta/rc on, can you update the version in the readme to match whatever you'll release?

**Comment by maennchen** [comment]
@c-rack ping (hex beta release)

**Comment by ImJoeWebb** [comment]
[Jobs with Second granularity](https://github.com/c-rack/quantum-elixir/blob/b49e291c0393b508276ddff94f7ddd07303da203/pages/configuration.md#jobs-with-second-granularity) gives an example with `import Crontab.CronExpression` but this isn't usually loaded when loading the configuration. Also it has `{"*/2", true}` instead of `~e(*/2)e` for the schedule.

**Comment by maennchen** [comment]
@ImJoeWebb Ow, Sigis do not work in Config at all. I'll make a PR for that doc section.

**Comment by c-rack** [comment]
@maennchen I will release 2.0.0-beta1 over this weekend

**Comment by maennchen** [comment]
@c-rack Do you want to give me permission for Hex? I could create the release then...

My Hex User: https://hex.pm/users/maennchen

**Comment by c-rack** [comment]
@maennchen I've added you to the list of owners. Please give it a try.

**Comment by maennchen** [comment]
`v2.0.0-beta.1` Beta is now on Hex

**Comment by maennchen** [comment]
@princemaple Follow up for https://github.com/c-rack/quantum-elixir/pull/206#issuecomment-312186676

The Idea was, to give the user the possibility to "copy" the quantum OTP process tree into it's own app. Also it should be possible for the user to communicate directly with this needed module (for simplicity)

**Comment by maennchen** [comment]
> I'm currently super busy. I wish I had more time so I could dive into this one, tear things apart and link them back together :)

I'd be happy to do some lifting if you tell me where the issues are. I'd like to do that now so that our major release is good.

**Comment by princemaple** [comment]
My points are

- client-server functions can be dedicated to the state related logics
- pure data transformations don't require spawning processes
- loading configs should not be tied to running processes, it's perfectly fine to just load it with Application.get_env and transform it with a normal function (i.e. not a client/server function)

If I were to make changes, my goals would be:
- `Scheduler`, `Supervisor` and `Runner` can be started separately
- Jobs can be created without having to spawn anything, simply passing the scheduler module and load configs from the application env (with some help from the passed in scheduler module)
- Make all client functions (i.e. the functions in scheduler) able to take a GenServer.server type as its target, they could default to runner (e.g. `server \\ runner(), ...other_args`)

**Comment by maennchen** [comment]
https://travis-ci.org/c-rack/quantum-elixir/jobs/248663271

Hmm. There still was an error on master....

**Comment by maennchen** [comment]
> loading configs should not be tied to running processes, it's perfectly fine to just load it with Application.get_env and transform it with a normal function (i.e. not a client/server function)

I'm not sure that I agree on that. This way the config can be manipulated by the Module the user extends. There are many libraries in the Elixir ecosystem that change their code to do exactly that. (See Phoenix & Ecto)

**Comment by maennchen** [comment]
> Make all client functions (i.e. the functions in scheduler) able to take a GenServer.server type as its target, they could default to runner (e.g. server \\ runner(), ...other_args)

What would be the benefit of this?

**Comment by princemaple** [comment]
> Hmm. There still was an error on master....

Yep that one is in `quantum_test`, not the ones I fixed in `normalizer_test`
This one I could no reproduce locally.
My suggested changes would fix this and allow tests to run with `async: true`, but... :)

**Comment by princemaple** [comment]
> What would be the benefit of this?

flexibility :) I would be able to wire things however I want, when I want to, like when I mess with `global`. Also makes it easy to test.

**Comment by maennchen** [comment]
I wouldn't like to change the OTP Tree of the app without a very good reason.

With your suggestion with the server argument, the default stays in place. So we can change that easily.

**Comment by princemaple** [comment]
> I wouldn't like to change the OTP Tree of the app without a very good reason.

I'm OK with its current structure, that the scheduler starts the supervisor, and the supervisor supervises a task supervisor and quantum runner. Just looking to make it more flexible and isolated, how things start each other, how names are passed around, and how calls are made.

**Comment by maennchen** [comment]
You'd like to change the interface like this?

```diff
diff --git a/lib/quantum/scheduler.ex b/lib/quantum/scheduler.ex
index 1cf9abc..ae19122 100644
--- a/lib/quantum/scheduler.ex
+++ b/lib/quantum/scheduler.ex
@@ -75,8 +75,8 @@ defmodule Quantum.Scheduler do
         Supervisor.stop(pid, :normal, timeout)
       end
 
-      def add_job(job = %Job{name: nil}) do
-        GenServer.call(__runnner__(), {:add, {nil, job}}, __timeout__())
+      def add_job(server // __runner(), job = %Job{name: nil}) do
+        GenServer.call(server, {:add, {nil, job}}, __timeout__())
       end
       def add_job(job = %Job{name: name}) do
         if find_job(name) do
@@ -185,7 +185,7 @@ defmodule Quantum.Scheduler do
   @doc """
   Adds a new unnamed job
   """
-  @callback add_job(Quantum.Job.t) :: :ok
+  @callback add_job(GenServer.server, Quantum.Job.t) :: :ok
 
   @doc """
   Adds a new named job
```

**Comment by princemaple** [comment]
Yeah something like that. I recall seeing a few client functions with multiple clauses and different signatures. Might need to play with the function head a little bit.

**Comment by maennchen** [comment]
@princemaple I'm aware, I'll create a ticket & PR.

**Comment by maennchen** [comment]
If there are no objections, I'd like to do a stable release.

@c-rack What do you think about it?

**Comment by c-rack** [comment]
Yes, a stable release would be nice. Go ahead.

**Comment by maennchen** [comment]
🍻
