### ISSUE TITLE
Problem: Warning message example doesn't work

### ISSUE THREAD

**Issue by dnsbty** [c-rack/quantum-elixir#191]
I inherited an app that had set up quantum with the following config:
```
config :quantum, cron: [
  "*/15 * * * *": &CronJobs.perform_task/0
]
```
When building the app I received this warning:
```
[warn] Configuring the cron configuration is deprecated. Please use the new syntax instead.

Example:
config :quantum, your_app_name: [
  crons: ["*/15 * * * *": &CronJobs.perform_task/0]
]
```
When I switched to the specified format, my cron jobs no longer ran. I had to switch them to the format specified in the doc to get them to work again:
```
config :quantum, :my_app, cron: [
  "#{time_between} * * * *": &CronJobs.perform_crawl/0
]
```

It would be great to change the warning to avoid tripping up others who may run into the same problem.

**Comment by c-rack** [comment]
Which version do you use? Or are you using latest master?

**Comment by dnsbty** [comment]
That's in version 1.9.0

**Comment by c-rack** [comment]
OK, thanks! Would you mind to send a PR that fixes this?

**Comment by maennchen** [comment]
@c-rack Could you release the fix so we can close this issue?

**Comment by c-rack** [comment]
Sure, will do so today.

**Comment by c-rack** [comment]
Version 1.9.2 is released now:
https://hex.pm/packages/quantum/1.9.2
