### ISSUE TITLE
Documentation improvement suggestion/guidance

### ISSUE THREAD

**Issue by matthewlehner** [c-rack/quantum-elixir#196]
As I've been going through setting things up, I'm wondering about the structure of the documentation WRT macros. Specifically, the callbacks are documented, but they don't show up in the module that calls `use`.

I'm not sure what's idiomatic for Elixir, but moving the `@doc` tags into the macro definition allows you to call `h App.Scheduler.add_job` (or for me to get the docs from Alchemist right in Vim… :wink:). I've tried to find more info about this and can't seem to find any guidance within the docs. 
That said, judging by code from within Phoenix, it seems like the pattern there is that macro itself defines functions that require compile time configuration, and `import` is used for the other functions.

I can start work on either of these options (moving `@doc` tags, or refactoring, or both?), if either of them are a direction that seems right.

**Comment by maennchen** [comment]
That seems like a giod suggestion. I'd be happy to accept a PR.

**Comment by maennchen** [comment]
@matthewlehner Actually, that seems to work already...

```
iex(2)>h QuantumTest.Scheduler.add_job

                   @callback add_job(Quantum.Job.t()) :: :ok

Adds a new unnamed job


@callback add_job(Crontab.CronExpression.t(), Quantum.Job.task()) :: :ok | :error

Adds a new named job

```

**Comment by maennchen** [comment]
@matthewlehner With the PR #200, the implementing module will have a default `@moduledoc`. 

The functions all show the doc of the callback for the help. I don't think that more than that is needed.

If Alchemist doesn't show help from callbacks, I think we need to report that at Alchemist. (The functionality should likely be the same as the internal elixir help.)

**Comment by maennchen** [comment]
@matthewlehner Does this solve your problem or do we need to do further changes?

**Comment by maennchen** [comment]
Closed because of inactivity. Current implementation should be sufficient.
