### ISSUE TITLE
Ecto Dependency Divergence Error

### ISSUE THREAD

**Issue by primitive-type** [c-rack/quantum-elixir#203]
After adding `quantum` to my `mix.exs` file and running `mix deps.get`, the following error occurs: 

```
mix deps.get
Running dependency resolution...
Dependencies have diverged:
* ecto (https://github.com/elixir-ecto/ecto.git)
  different specs were given for the ecto app:

  > In apps/my_app/mix.exs:
    {:ecto, [env: :prod, git: "https://github.com/elixir-ecto/ecto.git", ref: "b0a17727f3a504f82bd4f3fde34d25ba6c649fec", override: true, manager: :mix]}

  > In deps/crontab/mix.exs:
    {:ecto, "~> 1.0 or ~> 2.0 or ~> 2.1", [env: :prod, hex: :ecto, optional: true]}

  Ensure they match or specify one of the above in your deps and set "override: true"
** (Mix) Can't continue due to errors on dependencies
```

As you can see, we already specify `override: true` for Ecto in our app's `mix.exs`, which is what the above message seems to be suggesting we need to do. However, no matter what, it keeps popping up and preventing a successful dependency resolution.

Elixir version: 1.4.2

**Comment by maennchen** [comment]
(It's even optional for `crontab`)

**Comment by maennchen** [comment]
@primitive-type Does this solve your issue? https://github.com/elixir-lang/elixir/issues/5622

**Comment by primitive-type** [comment]
@maennchen I don't believe so, as we are already on version 1.4.2 and the issue still occurred.

**Comment by maennchen** [comment]
@primitive-type Can you check that it happens with non-umbrella apps as well?

**Comment by primitive-type** [comment]
@maennchen I just set up a test non-umbrella app and everything worked fine, so it looks like this is just an issue for umbrella apps.

**Comment by maennchen** [comment]
@primitive-type Please try to put the overridden dependency into your umbrella root mix.exs.

**Comment by primitive-type** [comment]
@maennchen Thanks, that did the trick.

**Comment by maennchen** [comment]
Yay 🍻
