### ISSUE TITLE
Problem: Scheduler GenServer Namings / Target not flexible enough

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#207]
See #184

**Comment by maennchen** [comment]
@princemaple 

These definitions conflict. How'd you solve that?

```elixir
def add_job(server \\ __runner(), job)
def add_job(server, job = %Job{name: nil}) do
  GenServer.call(server, {:add, {nil, job}}, __timeout__())
end
def add_job(server, job = %Job{name: name}) do
  if find_job(name) do
    :error
  else
    GenServer.call(server, {:add, {name, job}}, __timeout__())
  end
end

def add_job(server \\ __runner(), schedule = %Crontab.CronExpression{}, task) when is_tuple(task) or is_function(task, 0) do
  job = new_job()
  |> Job.set_schedule(schedule)
  |> Job.set_task(task)
  add_job(server, job)
end
```

**Comment by princemaple** [comment]
What do you think about `{schedule, task}`? I personally don't mind this way but don't like it either. But I prefer this way to making all options a map or a special struct.

**Comment by princemaple** [comment]
> I personally don't mind this way but don't like it either.

in terms of using it as a function parameter hack. However, if a schedule plus a task does define a job, I think it's good semantically.

**Comment by maennchen** [comment]
@princemaple Sounds inconvenient, but reasonable.
