### ISSUE TITLE
Error thrown from invalid cron format after submitting a job

### ISSUE THREAD

**Issue by ninjanicely** [c-rack/quantum-elixir#209]
Here are my stats...
Elixir Version: 1.5.0-dev
Erlang/OTP: 19
quantum: 1.8.1

I have an application that allows users to enter cron formatted strings to schedule different tasks.
We validate these strings up front using CronTab.CronExpression.Parser.parse(cron_string) and catch most problems.
When a user enters a cron string with 6 stars and submits, the parser doesn't catch any error. When I submit the job to the quantum scheduler, I get an `:ok` from the scheduler, but when the job kicks off, it throws an error. (See sample below)

```iex> interval = "* * * * * *"
iex> CronTab.CronExpression.Parser.parse(interval)
{:ok, ~e[* * * * * *]}
iex> job = %Quantum.job{schedule: interval, task: fn -> IO.puts "Hello world!" end}
iex> Quantum.add_job(jon)
:ok
Task #PID<some pid> started from Quantum terminating
** (MatchError) no match of right hand side value: ["*", "*", "*", "*", "*", "*"]
    <omitting rest of stack trace>
```

I can link rest of stack trace if needed. 

From your POV, is the error in the CronTab parser (and I can make a bug report there) or is the error in the quantum package? --is there any error at all, should I just be catching this with some kinda regex in the user form?

(Also, this is my first bug post, so any advice would be appreciated.) 
Thanks!

**Comment by maennchen** [comment]
We'll need the stack trace for sure, then I can say more.

**Comment by maennchen** [comment]
Also please use `v1.9.2`.

**Comment by ninjanicely** [comment]
Boop, upgrading to `v.1.9.2` seems to have fixed the issue. I'll be sure to check for updates next time. Thanks!
