### ISSUE TITLE
Problem: Timezone is not normalized from Config

### ISSUE THREAD

**Issue by InoMurko** [c-rack/quantum-elixir#220]
`Application.get_env(:quantum, :core)
[cron: [sku: [schedule: "@daily", task: {Core.Sku, :import_sku},
   args: [], timezone: "America/Mexico_City"]]]`

gets compiled down to:

`Quantum.jobs
[sku: %Quantum.Job{args: [], name: :sku,
  nodes: [:"core_1@elixir-node_1"], overlap: true, pid: #PID<0.3806.60>,
  schedule: ~e[0 0 * * * *], state: :active,
  task: {Core.Sku, :import_sku}, timezone: :utc}]`

First, I think there's to many stars in the :schedule config, second since the timezone is set to Mexico City, that isn't UTC 00:00.

Using Q. 1.9.2

elixir --version
Erlang/OTP 19 [erts-8.3] [source-d5c06c6] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Elixir 1.4.2

**Comment by maennchen** [comment]
@InoMurko Correctly, the `timezone` property of the `Quantum.Job` should be the timezone you provided in the config. The schedule is therefore correct.

I'll try to replicate what exactly causes the bug.

**Comment by maennchen** [comment]
@InoMurko Can you please verify if the PR #221 fixes your issue?

Replace your quantum Deps with this to test.

```elixir
defp deps do
  [{:quantum, git: "https://github.com/jshmrtn/quantum-elixir.git", branch: "normalizer_timezone_fix"}}]
end
```

**Comment by InoMurko** [comment]
It looks like timezone is now correct. Can you explain to me what the extra `schedule: ~e[0 0 * * * *]` star means?

**Comment by maennchen** [comment]
Ow, didn't see that, that is likely to be incorrect too. Let me check that.

The cron format should only be six places in size if it has second precision.

**Comment by maennchen** [comment]
Ah, no... It is correct.

The cron format is six parts in size and if second precision is activated seven.

```
      * * * * * * *
      | | | | | | |
      | | | | | | +-- :year Year                 (range: 1900-3000)
      | | | | | +---- :weekday Day of the Week   (range: 1-7, 1 standing for Monday)
      | | | | +------ :month Month of the Year   (range: 1-12)
      | | | +-------- :day Day of the Month      (range: 1-31)
      | | +---------- :hour Hour                 (range: 0-23)
      | +------------ :minute Minute             (range: 0-59)
      +-------------- :second Second             (range: 0-59)
```

See https://github.com/jshmrtn/crontab/blob/master/lib/crontab/cron_expression.ex#L36-L44

**Comment by InoMurko** [comment]
Excellent, thanks!

**Comment by maennchen** [comment]
No problem, I'll create a patch release right away.
