### ISSUE TITLE
Problem: Running on exact node

### ISSUE THREAD

**Issue by alPacino** [c-rack/quantum-elixir#23]
We need to allow via config where certain/all job(s) should be run. Let's say we have three servers with the app deployed to. So we should be able to define which server to run jobs on (now all three servers will send a newsletter email). That may be configured as follows:
```
config :quantum, cron: [
  newsletter: [
    schedule: "@monthly",
    task: "Newsletter.send",
    nodes: ["myapp@server1"] # or :myapp@server1
  ]
]
```

**Comment by c-rack** [comment]
Not sure if that should be coded in quantum, as it could also be done as (without code change):
```elixir
config :quantum, cron: [
  newsletter: [
    schedule: "@monthly",
    task: "Newsletter.send",
    state: fn() -> case node() do :myapp@server1 -> true; _ -> false end end.()
  ]
]
```
This is just a minimal example, of course. There are more elegant solutions.

**Comment by alPacino** [comment]
This will not work with conform/exrm/edeliver because in this sample you define anonymous function which can't be stored in app's final config file.

**Comment by c-rack** [comment]
Ok, good point.

Then I would suggest to use the `:myapp@server1` format, as this makes it easier to compare against the `node()` call.

Do you want to work on this and send a PR?

**Comment by alPacino** [comment]
Actually both forms "myapp@server1" and :myapp@server1 can be used. We will just convert one type to another on matching.

Yes, I will work on this.

**Comment by alPacino** [comment]
A little bit busy now. Will be able to implement this in several days I hope. Sorry.

**Comment by c-rack** [comment]
Take your time. I can do a 1.4.0 release first to bring the new named job feature to public.

**Comment by c-rack** [comment]
@alPacino can we close this issue?
I would prepare a new release over weekend then.
