### ISSUE TITLE
Add a job in runtime

### ISSUE THREAD

**Issue by InoMurko** [c-rack/quantum-elixir#232]
My struct is:
`a = %Quantum.Job{args: [], name: :send_email,
 nodes: [:"core_1@elixir-node_1"], overlap: true, schedule: "@daily",
 state: :active,
 task: {Transaction.Archive.Email.Report, :send_full_report},
 timezone: "America/Mexico_City"}`

`Quantum.add_job(a)
:ok`

result:

`Quantum.jobs
[nil: %Quantum.Job{args: [], name: nil, nodes: [:"core_1@elixir-node_1"],
  overlap: true, pid: #PID<0.16507.65>, schedule: ~e[0 0 * * * *],
  state: :active,
  task: {Transaction.Archive.Email.Report, :send_full_report},
  timezone: "America/Mexico_City"},`

The name of the job appears to be nil.

```
Quantum.delete_job(nil)
%Quantum.Job{args: [], name: nil, nodes: [:"core_1@elixir-node_1"],
 overlap: true, pid: #PID<0.13332.65>, schedule: ~e[0 0 * * * *],
 state: :active,
 task: {Transaction.Archive.Email.Report, :send_full_report},
 timezone: "America/Mexico_City"}
```

**Comment by c-rack** [comment]
Thanks for reporting!

A pull request with a failing test and/or a bugfix would be very appreciated and will be merged quickly.

**Comment by kaiatgithub** [comment]
@InoMurko Are you using an older version of quantum? I am asking because the current Quantum.Job structure does not support the keys "args" and "nodes".

**Comment by InoMurko** [comment]
dev-1 branch that contains the timezone fix

**Comment by maennchen** [comment]
@InoMurko can you please test with the PR?

I'd recommend updating to the v2 versions. I don't think that we'll support anything besides security fixes for a long time.

**Comment by InoMurko** [comment]
Will do!
