### ISSUE TITLE
How does Quantum behave on app restart?

### ISSUE THREAD

**Issue by bpicolo** [c-rack/quantum-elixir#238]
This bit is unclear from docs. Seems there's no notion of persistent storage. Does that mean app restarts can/should either lose or duplicate tasks? Should I expect to need hot code reloading as a release mechanism to keep consistent?

**Comment by maennchen** [comment]
Currently there is no mechanism in place to handle this. I think that this would be a good thing to implement.


I'd be happy to merge a PR for that. (If someone wants to do this please wait for v2.1 though)

**Comment by maennchen** [comment]
Closed in favor of #240
