### ISSUE TITLE
Runtime Docs

### ISSUE THREAD

**Issue by Ironjanowar** [c-rack/quantum-elixir#239]
Hi! I think runtime configuration documentation is outdated in hexdocs.pm

Here is hexdocs:
https://hexdocs.pm/quantum/runtime.html#content

And here is the one that worked for me:
https://github.com/c-rack/quantum-elixir/blob/master/pages/runtime.md

Thank you so much for Quantum!! I'm using it a lot :D

**Comment by maennchen** [comment]
Hi,

Yes, it is currently outdated. I don't like to create releases of the library only for documentation changes. It will be updated in the next release.

Thanks!

(I'll close this issue with the next release)

**Comment by maennchen** [comment]
Will be released with #243 (`v2.1.0-beta.1`)
