### ISSUE TITLE
Problem: Coveralls always showing PR's as failed.

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#242]
Currently Coveralls always shows a PR's build as failed. This even happens if the coverage increases.

Could we configure Coveralls to only fail if the coverage decreases?

See:

https://github.com/lemurheavy/coveralls-public/issues/565#issuecomment-120924694

**Comment by c-rack** [comment]
Once we had 100% code coverage, so I set the threshold to 100% and let it fail otherwise.

I have updated the setting to 86% and fail on decrease by more than 1%.

**Comment by maennchen** [comment]
Great, thx
