### ISSUE TITLE
Release v2.1.0

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#244]
## Tasks for Release

* [X] Merge #230 
* [x] Manual Testing (Help Wanted)
* [X] (Postponed) ~~#246 (Dialyzer Warnings)~~

## Release Date

If no big issues come up, the stable release is planned to take place on 2017/09/10.

**Comment by maennchen** [comment]
@c-rack Should we release without fixing #246 ? Until now I haven't found someone to help me fix the issue.

**Comment by c-rack** [comment]
@maennchen sure, we can postpone that issue for a later release

**Comment by maennchen** [comment]
Replaced by #262
