### ISSUE TITLE
default_timezone does not work

### ISSUE THREAD

**Issue by shribe** [c-rack/quantum-elixir#247]
In 2.0.0, setting `default_timezone` as per the example in the docs does not work, jobs still fire on UTC. But setting `timezone` at the top level instead of inside any job does work.

I'm not sure whether you'd consider the error to be in the docs or the implementation. (Personally, I prefer it the way it is now and would change the docs. But that's not a strong preference.)

**Comment by maennchen** [comment]
@shribe The doc is wrong. The error has been corrected and will be in the next release. (The doc is already correct with `v2.1.0-beta.1`.)
