### ISSUE TITLE
v2.0.0 timezone issue

### ISSUE THREAD

**Issue by InoMurko** [c-rack/quantum-elixir#248]
`config :core, Core.Scheduler,  
   jobs: [
    [ name: :cvs_export,
      schedule: "@daily",
      task: {Transaction.Archive.Csv, :report, []},
      timezone: "America/Mexico_City"
    ]
  ]
`

produces:

`RezolveCore.Scheduler.jobs()`
output:
`[cvs_export: %Quantum.Job{name: :cvs_export, overlap: true,
  pids: ["core_1@elixir-node_1": #PID<0.3528.0>],
  run_strategy: %Quantum.RunStrategy.Random{nodes: :cluster},
  schedule: ~e[0 0 * * * *], state: :active,
  task: {Transaction.Archive.Csv, :report, []}, timezone: :utc}]`

So it's not picking the correct timezone...

**Comment by maennchen** [comment]
Hi @InoMurko 

Thanks for your report. I could reproduce the issue easily. I've already created a fix (#250). It should be released soon.
