### ISSUE TITLE
jobs stop running after Node connect / disconnects

### ISSUE THREAD

**Issue by randysecrist** [c-rack/quantum-elixir#264]
I am experimenting with distributed erlang using a CRDT counter API.  I've been using quantum to schedule background jobs; currently I have two.

1) . Heartbeat, every minute on just one of the nodes (Random) in the cluster.  This job also tries to connect all configured nodes in the cluster (in case some of the drop off or new ones are added via config).

2) . State Save;  this should run on all nodes every n seconds, currently set to 5 seconds.

Config reference:
https://github.com/randysecrist/dist_counter/blob/master/config/config.exs#L38-L42

The issue:
Still exploring this; but as I user docker stop/start on a node; eventually the State job stops running on all the nodes.  I have observed some GenServer like DOWN messages in the logs as some of the nodes come and go.

This is entirely a toy/hobby project ... but I am curious more how quantum works and I will be looking more into the messages I am seeing.  I am curious what (if any) guidance you can give me in terms of making sure the jobs don't die.

I think adding cron schedule jobs and controlling which nodes the jobs run on is a nice addition for a library like this.  Usage of disterl makes elrang/elixir unique.

Thanks for providing this library!

**Comment by maennchen** [comment]
Hi @randysecrist 

In theory most of the GenServers / GenStages / Supervisors should start with a :global name.
Therefore Erlang itself should check that there is always one process runing with those services.

Since that doesn‘t seem to work in your case, I‘ll try to reproduce the issue.

**Comment by maennchen** [comment]
@randysecrist Is there any way to reproduce the issue easily with your repository? I tried to run your docker-compose file and got no output at all & the logs are not mapped to the host anywhere.

**Comment by randysecrist** [comment]
you can see the log files by using docker exec

```docker exec -it counter1 /bin/bash```

I connect to counter1, counter2, and counter3 in three different terminals.

Then in a fourth, I will docker stop/start one of the counter nodes enough times where the State job stops running on one or some of the nodes.

![screen shot 2017-09-21 at 8 57 20 am](https://user-images.githubusercontent.com/141339/30702839-445160f4-9eab-11e7-8e20-843d18d6bc52.png)
![screen shot 2017-09-21 at 8 58 06 am](https://user-images.githubusercontent.com/141339/30702840-44635aac-9eab-11e7-9f4f-ea32cf00d6a3.png)

**Comment by randysecrist** [comment]
I have a few API routes which show which nodes are connected as well.
```
# ports map to counter1, counter2, counter3
curl -X GET localhost:7777/config
curl -X GET localhost:8888/config
curl -X GET localhost:9999/config
```

**Comment by randysecrist** [comment]
These are the messages I see in the log:

```
[2017-09-21,15:05:00.268] [counter2@10.5.0.6|dev],[info]  global: Name conflict terminating {API.Scheduler.TaskRegistry, #PID<17664.830.0>}

[2017-09-21,15:05:00.268] [counter2@10.5.0.6|dev],[info]  global: Name conflict terminating {API.Scheduler.ExecutionBroadcaster, #PID<17664.832.0>}

[2017-09-21,15:05:00.268] [counter2@10.5.0.6|dev],[info]  global: Name conflict terminating {API.Scheduler.ExecutorSupervisor, #PID<17664.833.0>}

[2017-09-21,15:05:00.268] [counter2@10.5.0.6|dev],[info]  global: Name conflict terminating {API.Scheduler.JobBroadcaster, #PID<17664.831.0>}
```

**Comment by randysecrist** [comment]
I've also seen these; which happen if I down a node.  (Could be normal)

```
[2017-09-21,15:06:35.055] [counter3@10.5.0.7|dev],[error] Task #PID<0.1331.0> started from #PID<0.1330.0> terminating
** (stop) exited in: GenServer.call({API.State, :"counter2@10.5.0.6"}, :view, 500)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:774: GenServer.call/3
    (api) lib/api/state.ex:29: anonymous fn/4 in API.State.merge/2
    (elixir) lib/enum.ex:1811: Enum."-reduce/3-lists^foldl/2-0-"/3
    (api) lib/api/cron.ex:14: API.Cron.save_state/0
    lib/quantum/executor.ex:98: Quantum.Executor.execute_task/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:36: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: #Function<6.59732182/0 in Quantum.Executor.run/3>
    Args: []
```

```
[2017-09-21,15:06:34.398] [counter1@10.5.0.5|dev],[info]  GenStage consumer #PID<0.335.0> is stopping after receiving cancel from producer #PID<0.334.0> with reason: :killed

[2017-09-21,15:06:34.419] [counter1@10.5.0.5|dev],[error] GenServer API.Scheduler.ExecutorSupervisor terminating
** (stop) killed
Last message: {:DOWN, #Reference<0.3739719892.2264399875.43245>, :process, #PID<0.334.0>, :killed}
State: %ConsumerSupervisor{args: {{:global, API.Scheduler.ExecutionBroadcaster}, API.Scheduler.Task.Supervisor, {:global, API.Scheduler.TaskRegistry}}, children: %{}, max_restarts: 3, max_seconds: 5, mod: Quantum.ExecutorSupervisor, name: {:global, API.Scheduler.ExecutorSupervisor}, producers: %{}, restarting: 0, restarts: [], strategy: :one_for_one, template: {Quantum.Executor, {Quantum.Executor, :start_link, [{API.Scheduler.Task.Supervisor, {:global, API.Scheduler.TaskRegistry}}]}, :temporary, 5000, :worker, []}}
```

**Comment by maennchen** [comment]
Hmm....

The messages that a node was killed is perfectly normal since you really killed the node. OTP will then restart the global processes that were killed.

What could also happen is that the execution of a job was requested by the [`Quantum.Executor`](https://github.com/c-rack/quantum-elixir/blob/710ca519069a6c588e0a1f8bf8a4ee8ba9d616e3/lib/quantum/executor.ex) and the node goes down before it finished.

**Comment by randysecrist** [comment]
From a design perspective ... what is supposed to do the coordination of starting up the job again on the remaining nodes when there is a partition?

I don't think OTP just 'handles' it.  Something has to take those down messages and decide what to do with them right?

**Comment by maennchen** [comment]
OTP handles exactly that with the global name registration. I used this in many projects and it worked every time.

http://erlang.org/doc/man/global.html

I'm searching for any place where I forgot to link the process if the GenServer is already running in the cluster or similar problems.

**Comment by maennchen** [comment]
Workflow of `{:global, name}`:

* Start Server with `{:global, AnyName}`
  - Returned `{:ok, pid}` -> Tell to supervisor
    * Process was linked on start
    * Supervisor will retry on quit based on messages it receives from the link
  - Returned `{:error, {:already_started, pid}}` ->
    * Process was started already on another node and is not linked
    * We run `Process.link(pid)` on already running process
    * Supervisor will retry on quit based on messages it receives from the link

This is supposed to be able to recover from any node that goes down.

**Comment by h4cc** [comment]
I have the same symptoms here. I am using a the Random Strategy without overlap. global is set to true.

This is the error i get when a node is down:

```
[error] GenServer Platform.Quantum.ExecutorSupervisor terminating
** (stop) no connection
Last message: {:DOWN, #Reference<0.4115063335.1771307009.175294>, :process, #PID<0.11148.0>, :noconnection}
State: %ConsumerSupervisor{args: {{:global, Platform.Quantum.ExecutionBroadcaster}, Platform.Quantum.Task.Supervisor, {:global, Platform.Quantum.TaskRegistry}}, children: %{}, max_restarts: 3, max_seconds: 5, mod: Quantum.ExecutorSupervisor, name: {:global, Platform.Quantum.ExecutorSupervisor}, producers: %{}, restarting: 0, restarts: [], strategy: :one_for_one, template: {Quantum.Executor, {Quantum.Executor, :start_link, [{Platform.Quantum.Task.Supervisor, {:global, Platform.Quantum.TaskRegistry}}]}, :temporary, 5000, :worker, []}}
```

Why is the `Platform.Quantum.Task.Supervisor` not global when i have `global: true` in my config?

**Comment by maennchen** [comment]
@h4cc The `TaskSupervisor` is not global on purpose. It should run on every single node.
The idea is that we can start jobs specifically on a node. I think we need it to not be global for that.

Correct me if I'm wrong with that assumption.

**Comment by gar3thjon3s** [comment]
I am seeing the same issue, and can reproduce it easily enough albeit not with the exact set of steps that seem to happen in production. If you create a project with a `global: true` config and start two named instances, say `a` and `b` and start the application on each *before* connecting the nodes, then when you subsequently connect them the naming conflict seen above will occur:

```
12:31:29.396 [info]  global: Name conflict terminating {Schedulefail.Scheduler.ExecutorSupervisor, #PID<20982.251.0>}
12:31:29.396 [info]  global: Name conflict terminating {Schedulefail.Scheduler.JobBroadcaster, #PID<20982.249.0>}
12:31:29.396 [info]  global: Name conflict terminating {Schedulefail.Scheduler.TaskRegistry, #PID<20982.248.0>}
12:31:29.396 [info]  global: Name conflict terminating {Schedulefail.Scheduler.ExecutionBroadcaster, #PID<20982.250.0>}
```

When this happens erlang kills the extra global processes, but this leaves the Scheduler blocked in shutdown on one of the nodes. E.g:

`Process.info(Process.whereis(MyApp.Scheduler), :current_function)
{:current_function, {:supervisor, :shutdown, 2}}`

And it never restarts. This causes errors about the node not running to appear on the other nodes:

```
12:32:00.011 [warn]  Node :"b@host" is not running. Job #Reference<0.3759171582.2998403073.2150> could not be executed.
```

and it is unable to accept new jobs. If you `Process.exit(<PID>, :kill)` the Scheduler process, it restarts fine and is happy again.

I'm assuming that somehow in production due to some kind of network disconnect perhaps, a node is losing connection to the global references and starting its own. When it reconnects, they are being killed and its Scheduler is becoming stuck in shutdown. Does this make any sense?

**Comment by maennchen** [comment]
Thank you very much @gar3thjon3s for the reproducible error! I'll try to figure out what happens and fix it.

**Comment by maennchen** [comment]
@gar3thjon3s I think I found the bug, a fix will shortly follow :)

**Comment by maennchen** [comment]
@gar3thjon3s, @h4cc, @randysecrist Can you check if #285 is fixing the issues you have?

**Comment by thehammer** [comment]
I can respond on behalf of @gar3thjon3s that we are no longer seeing the bug while using #285. Thank you, and stay awesome!

**Comment by maennchen** [comment]
@thehammer Perfect :)

**Comment by randysecrist** [comment]
@maennchen confirm; this appears to be fixed
