### ISSUE TITLE
Can I have a distributed lock with quantum-elixir

### ISSUE THREAD

**Issue by sailxjx** [c-rack/quantum-elixir#265]
I need to start phoenix on multiple servers, if I use quantum-elixir on every server, can I have only one job executing at the scheduled time?

**Comment by maennchen** [comment]
Yes. This is what the `global` option is for.

https://hexdocs.pm/quantum/configuration.html#run-quantum-as-a-global-process

**Comment by sailxjx** [comment]
@maennchen Thanks for your reply, I'll try it later

**Comment by sailxjx** [comment]
@maennchen I've tried the `global` option, however I found it not works on multiple processes.
I need to distribute the whole application on multiple machines and docker containers, can I keep only one job works at the scheduled time?

**Comment by maennchen** [comment]
Yes, that's what `global` is for. Do you still get multiple executions of a job?

**Comment by sailxjx** [comment]
@maennchen Yes, this is my config
```
config :jupiter, Jupiter.Scheduler,
  jobs: [{"* * * * *", {Jupiter.RobotJob, :save_card_query_result, []}}]
```

and my job module
```
defmodule Jupiter.RobotJob do
  def save_card_query_result do
    IO.puts("tick")
  end
end
```

If I start two processes, each process will print a 'tick' for every minute.

**Comment by maennchen** [comment]
What do both applications show for `Node.list`?

**Comment by sailxjx** [comment]
The `Node.list` shows nothing.

**Comment by maennchen** [comment]
You need to connect those nodes.

I haven't found a good article that explains it. Take a look at that (even if it is opinionated about the platform it's running on): https://substance.brpx.com/clustering-elixir-nodes-on-kubernetes-e85d0c26b0cf

**Comment by maennchen** [comment]
Doc for `Node.connect`: https://hexdocs.pm/elixir/Node.html#connect/1

**Comment by sailxjx** [comment]
@maennchen I've tried connect these nodes, it works as expected. Thanks for your help :)
