### ISSUE TITLE
Running a job every X minutes for a specific amount of time?

### ISSUE THREAD

**Issue by egeersoz** [c-rack/quantum-elixir#266]
For example, when a user's credit card is declined, I want to send them an email every 24 hours for 7 days, but no more.

How do I specify this when setting up a runtime quantum job?

**Comment by maennchen** [comment]
This is not the intended use of quantum.

You could however implement this by scheduling two jobs: 1) sending the email and 2) deleting the first job.

**Comment by egeersoz** [comment]
That's how I ended up doing it, but it's a bit convoluted. Since use cases like this are very common, I think it should be added to Quantum. But it's obviously your call. Cheers.

**Comment by maennchen** [comment]
Feature Request is tracked in issue #268
