### ISSUE TITLE
Distillery fail to release with quantum

### ISSUE THREAD

**Issue by QwertyJack** [c-rack/quantum-elixir#274]
As described [here](https://github.com/bitwalker/distillery/issues/359), ***an anonymous function*** causes the error. Not sure where is wrong.

**Comment by maennchen** [comment]
I think that there is no way to put anonymous funtion in the configuration of a release. You‘ll have to put the function into a module.

**Comment by QwertyJack** [comment]
Get it. Thanks.

**Comment by QwertyJack** [comment]
I found [this](https://github.com/c-rack/quantum-elixir/blob/master/pages/configuration.md#release-managers). 
PS: exrm now moves to [Distillery](https://github.com/bitwalker/distillery).
