### ISSUE TITLE
Cron running completely off time

### ISSUE THREAD

**Issue by alex88** [c-rack/quantum-elixir#284]
I have the this configuration:

```
config :my_app, MyApp.Scheduler,
  jobs: [
    {"0 5 * * *",  {MyApp.Scheduler, :restart_monitoring, []}},
    {"0 13 * * *", {MyApp.Scheduler, :restart_monitoring, []}},
    {"0 21 * * *", {MyApp.Scheduler, :restart_monitoring, []}},
    {"0 0 * * *",  {MyApp.Scheduler, :persist_csv_data, []}}
  ]
```

however looking at the logs generated by the `restart_monitoring` function, seems an execution has been started at 23:21:07 which is not even on 0 minutes, so shouldn't be a timezone issue, also the system clock (checked with `date`) seems correct, but even if it wasn't, syslog should report the wrong time, how should I debug this?

Update: after restarting the server seems ok, could it be that the clock was out of sync when the server started? Or it crashed by a process taking too much time and after restart the timing wasn't correct?

**Comment by alex88** [comment]
Sorry sorry, stupid stupid stupid question :D

**Comment by maennchen** [comment]
@alex88 Do you still run into the issue?

**Comment by alex88** [comment]
@maennchen not really, I've restarted and updated the system clock using ntpd and it seems to work, however I've left it open just in case someone could somehow give some advice in how to debug a situation like that in case it happens again

**Comment by maennchen** [comment]
@alex88 It doesn't seem to happen for other people. I'll close the issue for now and reopen if someone else has a similar problem.
