### ISSUE TITLE
Support of 1 Branch

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#287]
Should we continue to support the `v1` versions?

If not, should we flag them as retired on hex.pm?

**Comment by c-rack** [comment]
Hex.pm docs say _"Mark a package as retired when you no longer recommend it’s usage. A retired is still resolvable and usable but it will be flagged as retired in the repository and a message will be displayed to users when they use the package."_

As we would always recommend to use v2, it makes sense to mark v1 as retired, yes.

**Comment by maennchen** [comment]
@c-rack Ok, I'm on it
