### ISSUE TITLE
Aggressive retirement

### ISSUE THREAD

**Issue by benwilson512** [c-rack/quantum-elixir#288]
Hey,

Can I get some clarification on why every version on hex other than the most recent is retired? In general retirement indicates that something is wrong with the package, such that using it is dangerous or likely to cause malfunction.

**Comment by maennchen** [comment]
Hey @benwilson512 

All versions of the v2.1 branch had a problem with the executor that could break and leave the system in a non recoverable state.

The v1 branch was retired since it is bot supported anymore. (See #287 )

**Comment by benwilson512** [comment]
Fair enough, thanks!
