### ISSUE TITLE
Problem: Elixir 1.6 & Code Styling

### ISSUE THREAD

**Issue by maennchen** [c-rack/quantum-elixir#291]
* Add Elixir `1.6` to Travis CI
* Add `.formatter-exs`
* Reformat all of the code using `mix format --check-equivalence`
* Add Travis Job to check Format ([see here](https://github.com/jshmrtn/crontab/blob/master/.travis.yml))
* Consider moving `inch.report` and `coveralls.travis` into their own jobs.

**Comment by c-rack** [comment]
C4 process says _"A patch SHOULD be a minimal and accurate answer to exactly one identified and agreed problem"_. Wouldn't it be better to split this issue into 5 smaller issues?

**Comment by maennchen** [comment]
I can do that. But first I have to figure out why the formatter is exclaiming on Travis Ci and not on my machine.
