### ISSUE TITLE
Compile Error v2.2.3 in execution_broadcaster.ex - no super defined

### ISSUE THREAD

**Issue by weixiyen** [c-rack/quantum-elixir#302]
Hi there, using Elixir 1.6.1

Was upgrading from v2.0 to v2.2 and got this:

```elixir
== Compilation error in file lib/quantum/execution_broadcaster.ex ==
** (CompileError) lib/quantum/execution_broadcaster.ex:32: no super defined for child_spec/1 in module Quantum.ExecutionBroadcaster. Overridable functions available are: code_change/3, handle_call/3, handle_cancel/3, handle_cast/2, handle_info/2, handle_subscribe/4, terminate/2
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
could not compile dependency :quantum, "mix compile" failed. You can recompile this dependency with "mix deps.compile quantum", update it with "mix deps.update quantum" or clean it with "mix deps.clean quantum"
```

Erlang/OTP 20 [erts-9.2.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.6.1 (compiled with OTP 20)

**Comment by maennchen** [comment]
@weixiyen Was this a problem caused by `quantum` itself? I have never seen this error even though I use the same Elixir & Erlang version.

**Comment by suddenrushofsushi** [comment]
I'm seeing this error currently in 2.2.5, same version of OTP/Elixir
@weixiyen did you determine what was causing this?
