### ISSUE TITLE
quantum 2.2.3 using gen_stage 0.13.1 is expected?

### ISSUE THREAD

**Issue by kpanic** [c-rack/quantum-elixir#303]
Hi folks, today I tried to bump up our quantum dependency, however we got:

```elixir
quantum_test$ grep quantum mix.exs
      {:quantum, "~> 2.2.3"}
```

```elixir
quantum_test$ mix deps.get
Resolving Hex dependencies...
Dependency resolution completed:
  crontab 1.1.2
  gen_stage 0.13.1
  quantum 2.2.3
[...]
```
Is gen_stage 0.13.1 expected?
Because it seems that https://github.com/c-rack/quantum-elixir/compare/v2.2.2...v2.2.3#diff-07ce5722d5fdbc0633d2d509e6289798R23 will fail with gen_stage 0.13.1

Thanks for the nice library btw!

**Comment by maennchen** [comment]
Hi @kpanic 
Yes, this is expected. The library is compatible with the 0.12 & 0.13 branch.
Did you encounter any errors?

**Comment by kpanic** [comment]
I will double check tomorrow in another repo, however in that code base the culprit was that there were no `[]` in https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/executor_supervisor.ex#L23

**Comment by maennchen** [comment]
To the best of my knowledge, the notation without the brackets should emit a warning. It should run fine though. If that is not the case, I‘ll have a closer look.

**Comment by kpanic** [comment]
```elixir
warning: ConsumerSupervisor.init/1 expects a list with a single element
  (gen_stage) lib/consumer_supervisor.ex:307: ConsumerSupervisor.init/2
  (gen_stage) lib/consumer_supervisor.ex:324: ConsumerSupervisor.init/1
  (gen_stage) lib/gen_stage.ex:1834: GenStage.init/1
  (stdlib) gen_server.erl:365: :gen_server.init_it/2
  (stdlib) gen_server.erl:333: :gen_server.init_it/6
```

Yes you are right. It's a warning. Sorry, I did not read the notice, it seemed an error :) You can close the question I guess. Thanks!

**Comment by pmarreck** [comment]
And what if one is a bit OCD and wants to eliminate warnings as well as errors? My build is littered with them and I got here via Google trying to clean this particular one up. It literally appears every time I start the local server :/ (awesome library regardless!)

**Comment by maennchen** [comment]
@pmarreck It has been fixed. If you still get the warning, please delete your `_build` directory and build again from scratch.
