### ISSUE TITLE
Relax timex dependency

### ISSUE THREAD

**Issue by benrom** [c-rack/quantum-elixir#304]
The requirement for timex is:
> {:timex, "~> 3.1.13", optional: true}

Unfortunately the latest timex release for the 3.1 branch (3.1.25) was "retired" and it fails to compile. Could it be changed? Thanks.

**Comment by benrom** [comment]
Actually having removed my hex.lock I see more errors when I update deps, not sure if it's caused by quantum only or by the new hex version (0.17.3)

>Failed to use "gen_stage" (versions 0.13.0 and 0.13.1) because
>  apps/shared/mix.exs requires ~> 0.12
>  quantum (versions 2.2.0 and 2.2.1) requires ~> 0.12.2

>Failed to use "timex" (versions 3.2.0 and 3.2.1) because
>  apps/shared/mix.exs requires ~> 3.2
>  quantum (versions 2.2.0 to 2.2.3) requires ~> 3.1.13

**Comment by benrom** [comment]
The only way I could fix the dependency issue (tried `override: true`) was to set in the reste of my app using the same dependencies:
```
      {:gen_stage, "~> 0.12.2"},
      {:timex, "3.1.24"},
```

It looks like something in quantum configuration make its dependencies more important than others..

**Comment by maennchen** [comment]
@benrom Sure, I'll relax the dependency on timex. Why did you have to override gen_stage though? `~> 0.12` should work for both `0.12` and `0.13`.

**Comment by maennchen** [comment]
@benrom Opened a PR to relax the dependency. I'll do a release as soon as it is approved.

**Comment by benrom** [comment]
It should, that's why there's something I don't understand there. I have an umbrella project with the other definitions set above and quantum ~> 2.2.
Elixir version is 1.6.1 and I removed all of _build/ and deps/, it failed on mix deps.get with the errors listed above.

**Comment by maennchen** [comment]
Ah no, ignore my last comment. This is also because of `timex`... The PR should fix the problem.

**Comment by maennchen** [comment]
@benrom This should be fixed with `v2.2.4`.

**Comment by benrom** [comment]
Great, thanks!
