### ISSUE TITLE
GenStage throws an error on start

### ISSUE THREAD

**Issue by leifg** [c-rack/quantum-elixir#307]
Anyone else experiencing this weird warning when starting Quantum:

```elixir
warning: ConsumerSupervisor.init/1 expects a list with a single element
  (gen_stage) lib/consumer_supervisor.ex:307: ConsumerSupervisor.init/2
  (gen_stage) lib/consumer_supervisor.ex:324: ConsumerSupervisor.init/1
  (gen_stage) lib/gen_stage.ex:1834: GenStage.init/1
  (stdlib) gen_server.erl:365: :gen_server.init_it/2
  (stdlib) gen_server.erl:333: :gen_server.init_it/6
```

It seems that at some point a single item is passed to GenStage which throws an error. I briefly looked at the code but could not pin down the exact location where GenStage is initialized.

**Comment by maennchen** [comment]
This is because of a change in gen_stage in v0.13. We can fix the warning, but not while staying compatible with v0.12.

**Comment by maennchen** [comment]
At the point where we release`quantum v2.3.0`, I'll fix the warning and restrict to `gen_stage ~> 0.13`. Until then my hands are tied.

**Comment by maennchen** [comment]
Since there were more reports, we're working on a way to omit the warning. #309

**Comment by maennchen** [comment]
Released in `v2.2.5`

**Comment by benrom** [comment]
I can still see the warning running 2.2.5.
> Elixir 1.6.1

**Comment by maennchen** [comment]
@benrom Can you please execute this in `iex`:

`Quantum.Util.gen_stage_v12?()`

Do you get `true` or `false`?

**Comment by benrom** [comment]
> Quantum.Util.gen_stage_v12?()
> false

**Comment by maennchen** [comment]
Can you please `mix deps.compile quantum --force`? If you get `false`, then this should not happen.

**Comment by benrom** [comment]
When running `mix test` I still see the warning after running that command line (tested as well with `MIX_ENV=test`)

**Comment by maennchen** [comment]
@benrom `MIX_ENV=test mix deps.compile quantum --force` does this solve it?

**Comment by benrom** [comment]
that's what I tested.

```
$> MIX_ENV=test mix deps.compile quantum --force
==> quantum
Compiling 20 files (.ex)
Generated quantum app

$> mix test
==> shared
warning: ConsumerSupervisor.init/1 expects a list with a single element
  (gen_stage) lib/consumer_supervisor.ex:307: ConsumerSupervisor.init/2
  (gen_stage) lib/consumer_supervisor.ex:324: ConsumerSupervisor.init/1
  (gen_stage) lib/gen_stage.ex:1834: GenStage.init/1
  (stdlib) gen_server.erl:365: :gen_server.init_it/2
  (stdlib) gen_server.erl:333: :gen_server.init_it/6
```

**Comment by maennchen** [comment]
That makes no sense at all :( I still believe that this has something to do with the already compiled code. Could you delete your `_build` directory on rebuild from scratch?

**Comment by benrom** [comment]
What I've just tested:
```
rm -rf _build/
rm -rf deps/
mix deps.get
mix test
```
and it's all ok now!

Weird. Thanks anyway!

**Comment by maennchen** [comment]
@benrom I did some weird compile time stuff to get rid of this warning. Seems to be a bug with elixir I think. If more people have this problem, I'll file an issue with elixir.
