### ISSUE TITLE
Problem: Name conflict terminating TaskStagesSupervisor in cluster

### ISSUE THREAD

**Issue by xinz** [c-rack/quantum-elixir#311]
Hi,

I'm using `libcluster` to maintain the cluster nodes, here is the error log when start more than two nodes.

```
2018-02-27 11:56:19.422 [info] global: Name conflict terminating {QuantumDemo.Scheduler.TaskStagesSupervisor, #PID<20556.214.0>}

2018-02-27 11:56:19.441 [error] GenServer QuantumDemo.Scheduler.ExecutorSupervisor terminating
** (stop) killed
Last message: {:EXIT, #PID<0.214.0>, :killed}
State: %ConsumerSupervisor{args: {QuantumDemo.Scheduler.ExecutionBroadcaster, QuantumDemo.Scheduler.Task.Supervisor, QuantumDemo.Scheduler.TaskRegistry}, children: %{}, max_restarts: 3, max_seconds: 5, mod: Quantum.ExecutorSupervisor, name: QuantumDemo.Scheduler.ExecutorSupervisor, producers: %{#Reference<0.3152433937.331874307.203647> => {{#PID<0.217.0>, #Reference<0.3152433937.331874307.203647>}, 0, 0, 25, 50}}, restarting: 0, restarts: [], strategy: :one_for_one, template: {Quantum.Executor, {Quantum.Executor, :start_link, [{QuantumDemo.Scheduler.Task.Supervisor, QuantumDemo.Scheduler.TaskRegistry}]}, :temporary, 5000, :worker, [Quantum.Executor]}}
```

Reproduce steps:

1. Here is a reproduce repo https://github.com/xinz/quantum_demo
2. After the deps installed, start node ac1 as `$ iex --name ac1@127.0.0.1 -S mix`, and then start another node ac2 as `$ iex --name ac2@127.0.0.1 -S mix`, we will see the above error message.

I also found the related discussion https://github.com/c-rack/quantum-elixir/issues/272, could you please advice any about this issue?

Thanks a lot!

**Comment by maennchen** [comment]
This is the relevant part for you from the referenced issue:

> The name conflict always happens if you start two (or more) nodes and put them in the same cluster later. As soon as they are part of the same cluster, the worker names are duplicated and all except one worker of the same name will be instantly killed.
> 
> If you see this error, you either had a netsplit or you started the node before clustering it. This is something that I saw to happen using libs that join the cluster in runtime like [`libcluster`](https://github.com/bitwalker/libcluster).
> 
> Since the workers are literally killed and not stopped, there is no way to handle a conflict gracefully. (I don't know how to solve that problem without altering erlang otp)

**Comment by xinz** [comment]
Appreciate for your reply, I found this thread https://github.com/bitwalker/libcluster/issues/40 as well, do you have any suggestions we can resolve this issue when using `libcluster`?

**Comment by maennchen** [comment]
@xinz Which strategy of `libcluster` are you using?

**Comment by maennchen** [comment]
I can't say if you can ignore this. That really depends on your use case.

If you only have jobs in your configuration (which you don't mind running twice) and no dynamic jobs, you can probably ignore the warnings.

**Comment by xinz** [comment]
@maennchen , I'm using `Cluster.Strategy.Epmd` as the strategy of `libcluster`.

Indeed, I hope the job can be daily executed as expected, I had occurred the job execution missing case when randomly in some one node.

**Comment by maennchen** [comment]
@xinz Do you have the newest version of quantum?

**Comment by xinz** [comment]
Yes

**Comment by maennchen** [comment]
With the newest version no jobs from your configuration should go missing. You might not see them on Node A since it runs on Node B. But it should always run. (Only talking of configured jobs and not dynamic ones though.)

I can not really help you with this problem except telling you that you need to ensure, that the clustering is happening before quantum is starting. If quantum is already running and you're joining a cluster that already contains quantum you're going to have conflicts and therefore the scheduler is killed. There is no way to handle those conflicts gracefully (like merging the state of the two conflicting schedulers) since OTP is not giving us any interfaces to do so.

**Comment by maennchen** [comment]
PS: If you're using the strategy `Epmd` you could also just use a `sys.config`, which would eliminate all of those problems.

https://dockyard.com/blog/2016/01/28/running-elixir-and-phoenix-projects-on-a-cluster-of-nodes

**Comment by xinz** [comment]
> With the newest version no jobs from your configuration should go missing. You might not see them on Node A since it runs on Node B. But it should always run. (Only talking of configured jobs and not dynamic ones though.)

Sorry that I didn't notice my staging environment was not the newest version of `quantum`,  I'm using the configured jobs, after upgrade `quantum` to the newest version, I will watch the job missing case, if the job will execute in any random node of the cluster, that's would be great for me.

> PS: If you're using the strategy Epmd you could also just use a sys.config, which would eliminate all of those problems.

Thanks a lot for this recommend, but I'm currently depend the `Swarm` (with `libcluster`) to maintain multi registered processes in cluster.

Again, thank you very much for your help.

**Comment by maennchen** [comment]
> Thanks a lot for this recommend, but I'm currently depend the `Swarm` (with `libcluster`) to maintain multi registered processes in cluster.

If I remember correctly, there's no need to use both `libcluster` and `swarm` anymore. If you use a strategy like kubernetes `libcluster` makes total sense, but if you use `Epmd` I would remove `libluster`.

**Comment by xinz** [comment]
👍 @maennchen thanks a lot, I will try to do that.

**Comment by maennchen** [comment]
@xinz I'm going to close this issue for now. If you have any questions, please reopen it.
