### ISSUE TITLE
Daylight Savings Bug 2

### ISSUE THREAD

**Issue by baldmountain** [c-rack/quantum-elixir#322]
This may be related to the other daylight savings bug but at the switchover from 2:00am to 3:00am (hour forward) my app used 100% CPU and Mesos said "Too much CPU for you" `kill -9`.  What I think happened is quantum saw that a whole bunch of tasks (the ones between 2:00am and 3:00am) hadn't run and tried to catch up by running them ALL. This is really bad for my app.

This makes me nervous about when the clocks get set back in the fall. Will quantum not run any tasks for an hour when the clocks are set back an hour?

Generally speaking I don't want quantum to ever try and catch up or retry failed tasks. Just move on to the next event.

**Comment by c-rack** [comment]
Maybe related to #321

**Comment by c-rack** [comment]
@baldmountain Thanks for reporting. Any PRs to solve this are very appreciated.

**Comment by c-rack** [comment]
@baldmountain running Quantum in UTC instead of a local timezone would prevent this bug, if there is no fix available until then

**Comment by maennchen** [comment]
@baldmountain I have found the error. Using UTC will not help to fix the issue. I‘m quite certain that this is the same issue as #321. I‘m closing this as a duplicate.
