### ISSUE TITLE
sleep till next action

### ISSUE THREAD

**Issue by norbu09** [c-rack/quantum-elixir#4]
would be nice to sleep till the next action instead of waking up every second. https://github.com/erlware/erlcron does that quite nicely.

**Comment by c-rack** [comment]
Thanks for pointing this out. I agree that waking up every second is too much, so I just pushed https://github.com/c-rack/quantum-elixir/commit/c307cf38e6bd689ea9b55326e8329747a6662b82 that changes to waking up every minute instead.

Waiting until next action might introduce too much complexity to the project and one wake up every minute should not harm. What do you think?

**Comment by dantswain** [comment]
IMHO waking up every minute (or even every second, really) is fine for an Erlang process.

**Comment by c-rack** [comment]
@dantswain I agree.

@norbu09 Do you think the change to one wake up per minute would be sufficient to close this issue? I would release then a new version tomorrow.

**Comment by norbu09** [comment]
happy to close the issue, just wanted to point out how others solved it. I may start using this in a project I currently write, if I get around adding the functionality in here I'll create a PR.

**Comment by c-rack** [comment]
Glad to hear you consider Quantum for your project!
Version 1.2.0 that wakes up every minute has just been published to hex.pm.

@norbu09 It is up to you to close this issue now or to leave it open until a PR is submitted and merged.

**Comment by norbu09** [comment]
happy to close this finally, sorry for the delay
