### ISSUE TITLE
Problem: normalize_unnamed_job throws exception w/ argument

### ISSUE THREAD

**Issue by theoretick** [c-rack/quantum-elixir#43]
I just discovered a bug in v0.5.0 where [`Quantum.Normalizer.normalize_unnamed_job`](https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/normalizer.ex#L68) is not properly handling jobs that take arguments. Reproduction:

```elixir
iex(2)> ["* * * * * Kernel.node"] |> Enum.map(&Quantum.Normalizer.normalize/1)
[nil: %Quantum.Job{args: [], name: nil, nodes: [:nonode@nohost],
  schedule: "* * * * *", state: :active, task: {"Kernel", "node"}}]

iex(3)> ["* * * * * Kernel.node(self)"] |> Enum.map(&Quantum.Normalizer.normalize/1)
** (MatchError) no match of right hand side value: []
    (quantum) lib/quantum/normalizer.ex:68: Quantum.Normalizer.normalize_unnamed_job/1
    (quantum) lib/quantum/normalizer.ex:50: Quantum.Normalizer.normalize_job/1
    (quantum) lib/quantum/normalizer.ex:6: Quantum.Normalizer.normalize/1
     (elixir) lib/enum.ex:1043: anonymous fn/3 in Enum.map/2
     (elixir) lib/enum.ex:1387: Enum."-reduce/3-lists^foldl/2-0-"/3
     (elixir) lib/enum.ex:1043: Enum.map/2
```

Sorry for the convoluted execution job, I had to find a STDLIB method that optionally took an argument to make this easily reproducible, hence `node`.

---
**Edit:** In looking through the usage examples there is appears to be few cases of argument passing except the use of `args` w/ named jobs.

It'll require a bit of a refactor as I dont see an easy way to enable argument passing here (fix regex, pass opts to `normalize_task`, etc etc) so maybe it should just be made clear its a limitation within the readme?  Not sure how you would like to proceed.

**Comment by alPacino** [comment]
@theoretick I guess you mean v1.5.0 :)

Actually usage examples describe task definition w/o args:
```
"* * * * *": {MyApp.MyModule, :my_method}
```
and
```
"* * * * * MyApp.MyModule.my_method"
```
Otherwise you should be able to send any parameter (e.g. functions):
```
"* * * * * MyApp.MyModule.my_method(fn(a, b) -> a + b end)"
```
but it's wrong way to define args. For this case you should use named jobs. Or it is possible to implement support for the following:
```
"* * * * *": {MyApp.MyModule, :my_method, [1, 2, 3]}
```

Anyway I think you just can change your config from
```
config :quantum, cron: [
  "* * * * * Kernel.node(self)"
]
```
to
```
config :quantum, cron: [
  some_job_name: [
    schedule: "* * * * *",
    task: &Kernel.node/1,
    args: [self]
  ]
]

```
Or for realtime job creation (from your example):
```
j = [
  schedule: "* * * * *",
  task: &Kernel.node/1,
  args: [self]
]
[{nil, j}] |> Enum.map(&Quantum.Normalizer.normalize/1)
```

**Comment by c-rack** [comment]
@theoretick Thanks for reporting!
Our documentation should be improved on this point. PRs are welcome.

And if someone wants to implement support for @alPacino's idea `"* * * * *": {MyApp.MyModule, :my_method, [1, 2, 3]}`, PRs are welcome, too :-)

**Comment by theoretick** [comment]
Ha, yes v1.5.0.  I ended up doing as you described replacing my config w/ `"* * * * * MyApp.MyModule.my_method(fn(a, b) -> a + b end)"` to get it working, but I wouldn't think this behavior is expected and seems limited.

It wasn't clear to me if the usage examples lacked args because that was the nature of the code or because it was a limitation of those methods of job declaration.

If named jobs is the suggested method of argument passing, perhaps that should be noted in the readme?  But as a user, I'd expect to be able to pass methods outside of either a fn closure or named job.

**Comment by theoretick** [comment]
Fixed in https://github.com/c-rack/quantum-elixir/pull/47
