### ISSUE TITLE
Problem: job names can only be atoms and can't be GC

### ISSUE THREAD

**Issue by luishurtado** [c-rack/quantum-elixir#49]
Currently only atoms are allowed as job names. This can be a potential security concern if jobs are created/deleted on demand. Basically after the job is deleted the atom used for the job name is not garbage collected. Job names should be any type and not only atoms.

I'm working on changes to "fix" this but want to know opinions in the mean time.

**Comment by alPacino** [comment]
@luishurtado :+1: Good point. I'm agree with that.

**Comment by c-rack** [comment]
@luishurtado Thanks! Guess we can close this issue then?
