### ISSUE TITLE
Task crashing for cron with "@reboot" 

### ISSUE THREAD

**Issue by wicliff** [c-rack/quantum-elixir#57]
When Cron is trigged on reboot, the task runs properly and exits. But after sometime this error shows up in log and executes the task again

```
[error] Task #PID<0.6628.0> started from Quantum terminating
** (MatchError) no match of right hand side value: ["@reboot"]
    (quantum) lib/quantum/executor.ex:31: Quantum.Executor.execute/2
    (elixir) lib/task/supervised.ex:74: Task.Supervised.do_apply/2
    (elixir) lib/task/supervised.ex:50: Task.Supervised.reply/3
    (stdlib) proc_lib.erl:239: :proc_lib.init_p_do_apply/3
Function: &Quantum.Executor.execute/2
```

Using this on Elixir 1.1.1, Phoenix 1.0.4

**Comment by c-rack** [comment]
@wicliff Thanks for reporting!

I have fixed this in #58.
An updated version of Quantum will be released shortly after it is merged.

**Comment by wicliff** [comment]
:+1: 
That is quick work! Appreciate the library, nicely done.

**Comment by theoretick** [comment]
Good catch @wicliff and speedy fix @c-rack!

**Comment by c-rack** [comment]
Updated version 1.6.1 including the bugfix has been published to hex.pm:
https://hex.pm/packages/quantum
