### ISSUE TITLE
Quantum.add_job does not work properly

### ISSUE THREAD

**Issue by ramstein74** [c-rack/quantum-elixir#65]
hello
Quantum.add_job("1 * * * *", fn -> :ok end) does not set the function to run every minute
If if do 
Quantum.jobs()
i see that the pid is set to nill

![image](https://cloud.githubusercontent.com/assets/1210858/12447627/033ef4f0-bf69-11e5-93d5-4cfe23565577.png)

If i put the tasks in the config file it works and the pid is set!

**Comment by c-rack** [comment]
@ramstein74 You say "run every minute", but your crontab spec says "every hour at minute 1". The correct crontab spec to run every minute must be `* * * * *`, not `1 * * * *`.
See: https://github.com/c-rack/quantum-elixir#crontab-format

Just tested with the correct crontab format and it works as expected and stores the PID.

**Comment by ramstein74** [comment]
yes you are right. I changed to * * * * * and still does not work.

**Comment by c-rack** [comment]
Please note that you have to wait until next full minute until the job is executed for the first time.

Please change the function to `fn -> IO.puts "tick" end` to see in console if the job executes.

For me, it looks like this:
```elixir
iex(1)> Quantum.jobs
[]
iex(2)> Quantum.add_job("* * * * *", fn -> IO.puts "Tick" end)
:ok
iex(3)> Quantum.jobs
[nil: %Quantum.Job{args: [], name: nil, nodes: [:nonode@nohost], overlap: true,
  pid: nil, schedule: "* * * * *", state: :active,
  task: #Function<20.54118792/0 in :erl_eval.expr/5>}]
iex(4)> Tick
iex(4)> Quantum.jobs
[nil: %Quantum.Job{args: [], name: nil, nodes: [:nonode@nohost], overlap: true,
  pid: #PID<0.159.0>, schedule: "* * * * *", state: :active,
  task: #Function<20.54118792/0 in :erl_eval.expr/5>}]
```
I have to wait between (3) and (4), of course.

**Comment by ramstein74** [comment]
2016-01-20 12:52 GMT+00:00 Constantin Rack <notifications@github.com>:

> Quantum.add_job("* * * * *", fn -> IO.puts "Tick" end)


I forgot the IO.puts
i had
Quantum.add_job("* * * * *", fn ->  "Tick" end)
solved!

Thank you
Antonio

**Comment by c-rack** [comment]
You are welcome!

**Comment by c-rack** [comment]
@ramstein74 By the way, if you like Quantum, staring it at GitHub would be very appreciated. Thanks! :-)

**Comment by ramstein74** [comment]
Done.
Thank you

2016-01-20 15:51 GMT+00:00 Constantin Rack <notifications@github.com>:

**Comment by ramstein74** [comment]
Hello again.
Another question.
I need to block a task from running again if the previous time it runs did not complete for some reason.
I need to kill it first.

My scenario is : many tasks that connect to ftp servers to collect data.
Some tasks runs every 5 minutes and sometimes they don' t complete in 5 minutes for some reason.
In that case i dont want to throw another task, i want to kill the previous task first.
Can i do that with quantum.
I tested it and seems to me that it doesnt care. if throws another task even if it is still running.

**Comment by c-rack** [comment]
Hi Antonio, thank you for your question. As this issue is already closed and your question is unrelated to this issue, please open a new issue – next time :-)

Regarding your question, Quantum already supports a `overlap: false` option which prevents Quantum to start a new task if the previous one is not finished yet, see:
https://github.com/c-rack/quantum-elixir#named-jobs

The documentation for this feature could be better but I am working on it.
