### ISSUE TITLE
how to specify overlap in config?

### ISSUE THREAD

**Issue by ramstein74** [c-rack/quantum-elixir#66]
i have this 
config :quantum, cron: [
    "*/10 * * * *": {"Tasks.Fabrica.Ps1", :load},

how do i specify overlap=false? what does false mean? if the old task hangs it never runs again righ?

also i need that a task be limited a certain amount of time to run. IF if does not succeed in that time it should be killed. Or evem simpler if i define a task interval of x minutes it should complete in that time otherwise should be killed so the next call can run again.

Can Quantum do this?

Thank you

**Comment by c-rack** [comment]
Regarding your first question ("how to specify"), here is an example:
```elixir
config :quantum, cron: [
  ps1: [
    schedule: "*/10 * * * *",
    task: {"Tasks.Fabrica.Ps1", :load},
    overlap: false
  ]
]
```

`false` means that the next run is suspended until the previous job has been finished. So yes, if the old task hangs, it never runs again.

Quantum has currently no timout mechanism as described, but it can be implemented very easily within your task. See section about "send and receive" here:
http://elixir-lang.org/getting-started/processes.html

You simply need to wrap your task within a `receive do` / `after` / `end` block.

If this answers your questions, please close this issue.

**Comment by ramstein74** [comment]
2016-01-21 11:11 GMT+00:00 Constantin Rack <notifications@github.com>:

>  ps1: [
>     schedule: "*/10 * * * *",
>     task: {"Tasks.Fabrica.Ps1", :load},
>     overlap: false
>   ]
>
>
Is there a way to just change the global default to false ?
Having 30 and counting tasks could simplify a litle.
About the send and receive i will look at it.
Thank you once again.

**Comment by c-rack** [comment]
There is no such feature to change the default of an option yet, sorry.
Feel free to open another issue with this as a feature request.
