### ISSUE TITLE
Problem: setting overlap doesn't have any effect

### ISSUE THREAD

**Issue by mosic** [c-rack/quantum-elixir#71]
Hi, thanks for making this library. I'm having trouble configuring the tasks to not overlap and I'm not sure if I'm doing something wrong with the configuration or if it's a bug.

This is the configuration I used:

``` elixir
config :quantum,
  default_overlap: false,
  cron: [
    snapshot_cleanup: [
      overlap: false,
      task: "EvercamMedia.Snapshot.Cleanup.init",
      schedule: "* * * * *",
    ]
  ]
```

Checking from `iex` everything seems to be configured correctly:

``` elixir
iex(1)> Application.get_env(:quantum, :cron)
[snapshot_cleanup: [overlap: false, task: "EvercamMedia.Snapshot.Cleanup.init",
  schedule: "* * * * *"]]

iex(2)> Application.get_env(:quantum, :default_overlap) 
false
```

But the task is still set to `overlap: true`:

``` elixir
iex(3)> Quantum.jobs                                    
[snapshot_cleanup: %Quantum.Job{args: [], name: :snapshot_cleanup,
  nodes: [:nonode@nohost], overlap: true, pid: #PID<0.1041.0>,
  schedule: "* * * * *", state: :active,
  task: {"EvercamMedia.Snapshot.Cleanup", "init"}}]
```

I'm running the latest version of the master branch. Any suggestions?

**Comment by c-rack** [comment]
Thanks for reporting! It is a bug. A pull request addressing this issue has been submitted. As soon as it is merged, I will release a new version and publish to hex.pm. Meanwhile, you could try the `issue-71` branch if it solves the problem.

**Comment by mosic** [comment]
I just tried that branch and it works! Thanks for the quick turnaround.

**Comment by c-rack** [comment]
Thanks for confirmation. Now waiting for the merge. In meantime, feel free to star this project if you do not already. That would be very appreciated :smile:

**Comment by mosic** [comment]
No problem. Thanks for the reminder, I try to star all projects I'm using.
