### ISSUE TITLE
Local timezone doesn't seem to be working

### ISSUE THREAD

**Issue by marcaddeo** [c-rack/quantum-elixir#73]
I have the following in my `config/config.exs` file:

```elixir
config :quantum,
  cron: [
    "*/15 * * * *": fn -> Client.heart_beat() end,
    "*/45 * * * *": fn -> Client.get_players() end,
    "43 20 * * *": fn ->
      players = PlayerServer.get_players()

      [cinema] = players
      |> Enum.filter(fn (player) ->
        player.name == "HEOS HomeCinema"
      end)

      if cinema do
        Client.set_mute(cinema.pid, "on")
      end
    end,
  ],
  timezone: :local
```

The first two jobs run successfully, but the third that is supposed to run at `20:43` never runs. It's currently `20:45` where I live, so it should have run 2 minutes ago when I was testing it. Am I missing something to set it to local?

**Comment by c-rack** [comment]
Could you please run the following command in `iex` and see what it produces?
```elixir
iex(1)> :calendar.now_to_local_time(:os.timestamp)
{{2016, 1, 29}, {10, 10, 49}}
```
We are just relying on the Erlang `now_to_local_time` function, so it depends on the local time of your computer, not the local time of your location. Does the output match with your expected local time?

**Comment by marcaddeo** [comment]
@c-rack it does output my current local time (8:21 EST)

**Comment by c-rack** [comment]
OK, so could you please change your example to just print a `IO.puts "Tick"` to the console? We need to verify that it is actually Quantum not executing the job or the job not executing correctly. By this, we can just focus on Quantum code, regardless of your code.

Please try the following minimal configuration and set the hour/minute a few minutes in future according to your time zone:

```elixir
config :quantum,
  cron: [
    "30 10 * * *": fn -> IO.puts "Tick" end,
  ],
  timezone: :local
```

I would expect that it prints `Tick` as soon as the time matches, but please give it a try. Thanks!

**Comment by marcaddeo** [comment]
Using the following code at `9:30 AM` and waiting two minutes:

```elixir
config :quantum,
  cron: [
    "32 9 * * *": fn -> IO.puts "Tick" end,
  ],
  timezone: :local
```

No `Tick` :(

**Comment by theoretick** [comment]
Seems to work fine for me w/ the above configuration, local timezone and `"36 8 * * *"`.  @marcaddeo are you on v1.6.1?

**Comment by marcaddeo** [comment]
Yup, `mix.lock` says `1.6.1`. I'm running on OS X, but I doubt that should make a difference.

Let me try it in a blank project and see what I get.

**Comment by c-rack** [comment]
@marcaddeo Maybe the Quantum server has not been started at all. Have you added `:quantum` to the list of *applications* in your `mix.exs` as described in the setup? It is not enough to just add Quantum as dependency, it also needs to be started:
https://github.com/c-rack/quantum-elixir#setup

**Comment by theoretick** [comment]
FWIW I too am running it on OSX, elixir v1.2.0

**Comment by marcaddeo** [comment]
Okay, so running in a brand new project (`mix new quantum_test`) I DO get the `Tick` in local time. But, still not working in my real project.

Yes, I do have the `:quantum` application starting. Here's my `mix.exs`:

```elixir
defmodule ExHeos.Mixfile do
  use Mix.Project

  def project do
    [app: :ex_heos,
     version: "0.0.1",
     elixir: "~> 1.1",
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps]
  end

  # Configuration for the OTP application
  #
  # Type "mix help compile.app" for more information
  def application do
    [
      mod: {ExHeos, []},
      applications: [
        :logger,
        :nerves_ssdp_client,
        :quantum,
      ]
    ]
  end

  # Dependencies can be Hex packages:
  #
  #   {:mydep, "~> 0.3.0"}
  #
  # Or git/path repositories:
  #
  #   {:mydep, git: "https://github.com/elixir-lang/mydep.git", tag: "0.1.0"}
  #
  # Type "mix help deps" for more examples and options
  defp deps do
    [
      {:nerves_ssdp_client, git: "https://github.com/nerves-project/nerves_ssdp_client"},
      {:poison, "~> 2.0"},
      {:quantum, ">= 1.6.1"},
    ]
  end
end
```
The order of which the `:quantum` app gets started shouldn't matter, right?

Also, I'm running Elixir `1.1.1`. I'll update and see if it helps.

**Comment by marcaddeo** [comment]
Upgrading had no effect, but didn't really expect it to since you're testing with `1.1.0` on travis.

**Comment by marcaddeo** [comment]
Maybe this would help?

Wanna clone [marcaddeo/ex_heos](https://github.com/marcaddeo/ex_heos) and checkout the `scheduling` branch? I have the core functionality of the app commented out in the last commit (it wont run without actual Denon HEOS speakers on the network, should probably fix that!) so running with `iex -S mix` should just assist in testing the quantum stuff.

Maybe my code will run successfully on your machine? Which would be strange!

**Comment by c-rack** [comment]
@marcaddeo I have cloned your project and tested it. It was running fine and printed the "tick". Only thing I observed was that the system clock on the test machine was several seconds delayed compared to my computer, so the tick came a little bit "late". But I assume you have waited for a longer time without effect, don't you? I also started the project with `iex -S mix` to be able to see what `:calendar.now_to_local_time(:os.timestamp)` gives. Additionally, I had setup a second "tick"-job which runs just every minute (`* * * * *`), to see if Quantum is working at all. It is, as you said, strange...

**Comment by marcaddeo** [comment]
Yeah, I've left it running waiting for the tick.

This is really strange... lol. I was really hoping it didn't work on your system haha!

I guess the next thing to do when I get home is to litter your code with `Logger.log` to see what's going on.

**Comment by c-rack** [comment]
OK, please keep us updated :-)

**Comment by c-rack** [comment]
Any update on this issue?

**Comment by marcaddeo** [comment]
Haven't had a chance to look into it unfortunately :cry:

**Comment by dapdizzy** [comment]
Dudes, scheduling at a certain minute does not seem to work, i.e., "45 16 * * *" does not fire at 16:45
:calendar.now_to_local_time(:os.timestamp) outputs correct local time.
"* * * * *" works fine every minute
:quantum app is started. (dependency is used as given in re readme)

Scheduled function is trivial, so there's no suspicion the job fails itself, it's pretty clear it is not scheduled (not run at the expected time).

What would you suggest? I guess, it's a pretty major issue.

**Comment by marcaddeo** [comment]
@dapdizzy try converting your time to UTC, it will likely work then if you're having the same issue I was having.

**Comment by rolfhand** [comment]
Same here, location Amsterdam UTC+ 1
Job are executed at UTC.
Did some checks

```
iex(42)> now
&:calendar.now_to_local_time/1

iex(48)> :calendar.now_to_local_time :os.timestamp
{{2016, 2, 28}, {16, 13, 57}}      # OK localtime

'ex(49)> Quantum.Timer.tick                       
{{2016, 2, 28}, 15, 14}              # is UTC and not local.`
```

Created and tested a little different version for tick function:
```
iex(50)> Testtimer.tick                               
{{2016, 2, 28}, 16, 15}                 # OK  correct local time
```
Code:
```
def tick do
	case Application.get_env(:quantum, :timezone, :utc) do
  		:utc -> 
  			{d, {h, m, s}} = :calendar.universal_time
  		:local ->
  			{d, {h, m, s}} = :calendar.local_time
  	end
    	Process.send_after(self, :tick, (60 - s) * 1000)
	{d, h, m}
  end
```

**Comment by dapdizzy** [comment]
@marcaddeo Thank you, this worked out!
@rolfhand Thanks for your detailed answer! This clarifier and hels a lot!

I just want to state that this behaviour (which timezone should be used for time) should be well-documented and **bold-stated** in the readme.

Thanks!

**Comment by dapdizzy** [comment]
One more question: does it mean @midnight would schedule to UTC midnight, not a local one?

**Comment by marcaddeo** [comment]
@dapdizzy actually.. it is documented and bold in the [README](https://github.com/c-rack/quantum-elixir#timezone). I missed it too, though, when I started trying this library out. 

But I still have trouble getting the `:local` option to work, as you apparently are as well.

@c-rack could this have anything to do with the use of `unquote` in the [tick function here](https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum/timer.ex)? Does unquote only get run during compile-time? Would that make the `timezone: :local` configuration not do anything?

Just guessing here, never had a chance to revisit this :/

**Comment by dapdizzy** [comment]
@marcaddeo Oops... Seems to have messed things up a little bit. Sorry for complaining on the doc then.

**Comment by marcaddeo** [comment]
@dapdizzy are you using @rolfhand's code? Looks like there's a bug in it to me, it doesn't pass the `:os.timestamp` to either of the `:calendar` functions.

Maybe try this (completely untested):

```elixir
defmodule Quantum.Timer do

  @moduledoc false

  def tick do
    now = case Application.get_env(:quantum, :timezone, :utc) do
      :utc ->
        &:calendar.now_to_universal_time/1
      :local ->
        &:calendar.now_to_local_time/1
      timezone ->
        raise "Unsupported timezone: #{timezone}"
    end

    {d, {h, m, s}} = now.(:os.timestamp)
    Process.send_after(self, :tick, (60 - s) * 1000)
    {d, h, m}
  end
end
```

**Comment by theoretick** [comment]
Yeah, I'd speculate that this is an issue with the compile-time execution vs runtime. If one were to compile on a machine with a different timezone than their destination server, that could lead to a different configuration than expected.

**Comment by dapdizzy** [comment]
If it's in accordance with the documentation and does not contradict common sense, then it's perfectly fine. As I've said, I seem to have messed things up a little bit and was sure to expect local timezone as default accordind to documentation. Now I see that it seems to be good and there seems to be no issue at this point.

@marcaddeo I'm not actually using it. Just mentioned that it clarified the usage of configuration setting. I did not use the code.

**Comment by marcaddeo** [comment]
Oh, okay. So does `timezone: :local` work for you, @dapdizzy? And the problem was just that you missed it in the documentation?

**Comment by dapdizzy** [comment]
@marcaddeo It does not seem to. Just adedd `timezone: :local` as it is stated in the doc and scheduled a simple IO.puts "Hello" to "02 21 * * *" (it's 21:03 Moscow time now) and started the app using `mix run --no-halt`, nothing came out. Started the app before it was 21 local time to make it clear.

**Comment by kaiatgithub** [comment]
In my view the tick function should be changed the way @rolfhand suggested. Right now, the program picks up the timezone set at compile-time, or :utc, if nothing has been configured. So a configuration-change to :local after compilation has no effect.

**Comment by kaiatgithub** [comment]
The pull request #81 should fix this bug.

**Comment by rolfhand** [comment]
@marcaddeo my code works. I'm just using the shorter calendar functions .local_time and .universal.time  in stead of :calendar.now_to_local_time :os.timestamp.  It's running now in an application and fires the jobs at the right time.

**Comment by marcaddeo** [comment]
@rolfhand my bad! Didn't even notice the difference, d'oh!

@kaiatgithub woohoo! :+1:

**Comment by c-rack** [comment]
Thanks to everyone for working on this and to @kaiatgithub for the pull request!
