### ISSUE TITLE
Fail to compile when deploying to Heroku

### ISSUE THREAD

**Issue by taylorbrooks** [c-rack/quantum-elixir#75]
```bash
remote: -----> Compiling
remote: lib/quantum.ex:1: warning: redefining module Quantum
remote: lib/quantum/application.ex:1: warning: redefining module Quantum.Application
remote: ==> quantum
remote: Compiled lib/quantum/application.ex
remote: lib/quantum/executor.ex:1: warning: redefining module Quantum.Executor
remote: 
remote: == Compilation error on file lib/quantum/executor.ex ==
remote: ** (CompileError) lib/quantum/executor.ex:34: undefined function match/3
remote:     (stdlib) lists.erl:1337: :lists.foreach/2
remote:     (stdlib) erl_eval.erl:669: :erl_eval.do_apply/6
remote: 
remote: could not compile dependency :quantum, "mix compile" failed. You can recompile this dependency with "mix deps.compile quantum", update it with "mix deps.update quantum" or clean it with "mix deps.clean quantum"
remote: 
remote:  !     Push rejected, failed to compile elixir app
remote: 
```

Anyone get this yet? I just bumped to 1.6.1 from 1.3.2

**Comment by c-rack** [comment]
Try a `mix clean` first. If that does not help, please remove the entire `_build` directory and recompile (`mix compile`). It seems that some old files are still in place (hence the `redefining module` message). 

Please let me know if that worked (or not), thanks.

**Comment by taylorbrooks** [comment]
Hmm, it compiles fine locally. Lemme open an issue on the [buildpack repo](https://github.com/HashNuke/heroku-buildpack-elixir/issues) and see if they have any suggestions.

**Comment by c-rack** [comment]
So, is it not possible to delete the `_build` directory on the remote before the deploy?

**Comment by taylorbrooks** [comment]
Not from what I can tell.

**Comment by taylorbrooks** [comment]
Fixed by adding `elixir_buildpack.config`. Closing.

**Comment by barberj** [comment]
@taylorbrooks can you elaborate? is the file that you added `elixir_buildpack.config` empty?

**Comment by barberj** [comment]
@taylorbrooks nm i figured it out. Thanks
