### ISSUE TITLE
Problem: Could not allow to create another task with same name

### ISSUE THREAD

**Issue by ramstein74** [c-rack/quantum-elixir#76]
If i do Quantum.add_job("ticker", job) , it should not allow it to be created if already created before a task named "ticker".

**Comment by c-rack** [comment]
Thanks. Would you mind to send a pull request that fixes this?

**Comment by ramstein74** [comment]
I dont have sufficient knowledge.
Im just learning elixir for a task scheduler.
Your package is very good but i´m learning, stil...

**Comment by c-rack** [comment]
Then we have to wait until some else has this problem too and wants to invest his time to submit a patch.

**Comment by kaiatgithub** [comment]
Please see the following pull request for a proposed solution: #78

**Comment by c-rack** [comment]
Fixed by #78
