### ISSUE TITLE
Run a job once at specific time/date

### ISSUE THREAD

**Issue by ramstein74** [c-rack/quantum-elixir#77]
How can i run a task in the future only once at a specific time and date ?

Thank you

**Comment by c-rack** [comment]
Please see the [crontab format section in our readme](https://github.com/c-rack/quantum-elixir#crontab-format) and use your favorite search engine to learn more about "crontab", there is a lot of good documentation available online about this topic.

To answer your question, if you want to execute a task on Christmas at 8:30 AM for example, you would use as schedule:
`30 8 24 12 *`

This will execute the task every year.
If you want to restrict that to a specific year, you have to check for this in your task.
There is no way to restrict on a year currently.
