### ISSUE TITLE
Problem: Quantum GenServer restarts when one of the jobs crashes

### ISSUE THREAD

**Issue by luishurtado** [c-rack/quantum-elixir#82]
When one of the jobs crashes the caller process (GenServer Quantum) crashes too and it is restarted. The problem with this is that the jobs are hold in the state, when Quantum GenServer restarts the state is reset and the jobs added will be lost.

I have a failing test case that I'm about to push to a brach linked to this issue.

We have two options to fix this that I want to elaborate a little bit:

~~__Option 1__: move jobs to an Agent. Since the jobs table is a state we want to preserve during the live of the application we can move it to an Agent instead of a List in the Quantum GenServer state. This will avoid the jobs table to be lost when the Quantum GenServer restarts because one the children jobs crashed. 
_Note_: I'm not sure if because of the Quantum GenServer crashes all other monitored children jobs will crash too... I will try to write another test for this.~~
__UPDATE__: after creating a test case we can ensure sibling jobs crash when one of the other jobs crashes. This lead to not consider this option 1 as a solution to the bug.

__Option 2__: change `Task.Supervisor.async` to `Task.Supervisor.async_nolink` in `Quantum` [here](https://github.com/c-rack/quantum-elixir/blob/master/lib/quantum.ex#L134) 
The challenge with `Task.Supervisor.async_nolink` is that it is not available until Elixir version 1.2.0 and currently we are with Elixir `>= 1.0.0`
Because of the above we have 2 options:

1. upgrade the version of this library to use Elixir `>= 1.2.0` (all tests passes including the one I'm going to push).

2. stay in Elixir `>= 1.0.0` and write a function that do the same thing than `Task.Supervisor.async_nolink`

Before implementing anything I wanted to bring the discussion to the table and decide what is the best approach.

**Comment by luishurtado** [comment]
Update: I've pushed test case to branch `issue-82`

**Comment by luishurtado** [comment]
Update: another test case that proves sibling jobs crash when of the jobs crashes.

**Comment by c-rack** [comment]
I am perfectly fine to upgrade required Elixir version to `>= 1.2.0` and use `Task.Supervisor.async_nolink`. Would you mind to send a pull request based on your branch?

By the way, it would be better to use your own fork to publish branches. Maybe next time ;-)

**Comment by c-rack** [comment]
Closed by merging #84
