### ISSUE TITLE
question: how many jobs can one node hold?

### ISSUE THREAD

**Issue by trungpham** [c-rack/quantum-elixir#85]
Can the number of jobs be horizontally scaled if we add a new node to the cluster?
Or not possible because the `jobs` array is cloned on every node, rather than partitioned?

**Comment by c-rack** [comment]
Currently, the job configuration is per node and there is no automatic partioning or something similar.

If you want to add such a feature, however, feel free to submit a pull request.

Regarding your question in the title, the number of jobs per node is only limited by the memory of the BEAM VM.
