### ISSUE TITLE
Question: Any interest in per-job timezones?

### ISSUE THREAD

**Issue by smiley325** [c-rack/quantum-elixir#88]
I forked `quantum-elixir` to support per-job timezones (default behavior still matches the way quantum currently works), I just wanted to see if there was any interest in it being merged into the mainline; if so, I can make a clean, test-passing pull request for it. 

Basically it just adds a `timezone` field which can be any IANA timezone from `zone.tab` (e.g. "America/Chicago" or "UTC", defaults to Quantum application default).

**Comment by c-rack** [comment]
Yes, that would be really appreciated.

**Comment by smiley325** [comment]
Just created PR #90 regarding it

**Comment by c-rack** [comment]
Closed by merging #90
